INSERT INTO armes (arme_name) VALUES
    ('Knife'),
    ('Classic'),
    ('Shorty'),
    ('Frenzy'),
    ('Ghost'),
    ('Sheriff'),
    ('Stinger'),
    ('Spectre'),
    ('Bucky'),
    ('Judge'),
    ('Bulldog'),
    ('Guardian'),
    ('Phantom'),
    ('Vandal'),
    ('Marshall'),
    ('Operator'),
    ('Ares'),
    ('Odin');

INSERT INTO collections (collection_name) VALUES
    ('Kuronami'),
    ('Ion'),
    ('Oni'),
    ('Glitchpop'),
    ('Prime'),
    ('Spectrum'),
    ('Sentinel of the light'),
    ('Prelude to Chaos'),
    ("Gaia's vengance"),
    ('Reaver'),
    ('Radiant Entertainment System'),
    ('Arcane'),
    ('RGX'),
    ('Magepunk'),
    ('Elderflame'),
    ('Convex'),
    ('Champion 2021'),
    ('Champion 2022'),
    ('Champion 2023');

INSERT INTO skin (collection_id, arme_id, price, reduction, image_path, icone_path, background_path, description) VALUES
(1, 1, 20, NULL, NULL, NULL, NULL, 'Couteau Kuronami'),
(2, 1, 20, NULL, NULL, NULL, NULL, 'Couteau Ion'),
(3, 1, 20, NULL, NULL, NULL, NULL, 'Couteau Oni'),
(4, 2, 20, NULL, NULL, NULL, NULL, 'Classic Glitchpop'),
(5, 2, 20, NULL, NULL, NULL, NULL, 'Classic Prime'),
(6, 2, 35, NULL, NULL, NULL, NULL, 'Classic Spectrum'),
(3, 3, 20, NULL, NULL, NULL, NULL, 'Shorty Oni'),
(7, 3, 20, NULL, NULL, NULL, NULL, 'Shorty SOTL'),
(8, 3, 20, NULL, NULL, NULL, NULL, 'Shorty PTC'),
(5, 4, 20, NULL, NULL, NULL, NULL, 'Frenzy Prime'),
(4, 4, 20, NULL, NULL, NULL, NULL, 'Frenzy Glitchpop'),
(2, 4, 20, NULL, NULL, NULL, NULL, 'Frenzy Ion'),
(9, 5, 20, NULL, NULL, NULL, NULL, 'Ghost Gaia'),
(10, 5, 20, NULL, NULL, NULL, NULL, 'Ghost Reaver'),
(11, 5, 20, NULL, NULL, NULL, NULL, 'Ghost Radiant'),
(12, 6, 20, NULL, NULL, NULL, NULL, 'Sheriff Arcane'),
(13, 6, 20, NULL, NULL, NULL, NULL, 'Sheriff RGX'),
(, 6, 20, NULL, NULL, NULL, NULL, 'Sheriff Magepunk'),
(, 7, 20, NULL, NULL, NULL, NULL, 'Stinger Elderflame'),
(, 7, 20, NULL, NULL, NULL, NULL, 'Stinger Convex'),
(, 7, 20, NULL, NULL, NULL, NULL, 'Stinger Champion 2021'),
(, 8, 20, NULL, NULL, NULL, NULL, 'Spectre Champion 2022'),
(, 8, 20, NULL, NULL, NULL, NULL, 'Spectre Champion 2023'),
(, 8, 20, NULL, NULL, NULL, NULL, 'Spectre Champion 2024'),
(, 9, 20, NULL, NULL, NULL, NULL, 'Bucky Kuronami'),
(, 9, 20, NULL, NULL, NULL, NULL, 'Bucky Ion'),
(, 9, 20, NULL, NULL, NULL, NULL, 'Bucky Oni'),
(, 10, 20, NULL, NULL, NULL, NULL, 'Judge Glitchpop'),
(, 10, 20, NULL, NULL, NULL, NULL, 'Judge Prime'),
(, 10, 20, NULL, NULL, NULL, NULL, 'Judge Spectrum'),
(, 11, 20, NULL, NULL, NULL, NULL, 'Bulldog Oni'),
(, 11, 20, NULL, NULL, NULL, NULL, 'Bulldog SOTL'),
(, 11, 20, NULL, NULL, NULL, NULL, 'Bulldog PTC'),
(, 12, 20, NULL, NULL, NULL, NULL, 'Guardian Prime'),
(, 12, 20, NULL, NULL, NULL, NULL, 'Guardian Glitchpop'),
(, 12, 20, NULL, NULL, NULL, NULL, 'Guardian Ion'),
(, 13, 20, NULL, NULL, NULL, NULL, 'Phantom Gaia'),
(, 13, 20, NULL, NULL, NULL, NULL, 'Phantom Reaver'),
(, 13, 20, NULL, NULL, NULL, NULL, 'Phantom Radiant'),
(, 14, 20, NULL, NULL, NULL, NULL, 'Vandal Arcane'),
(, 14, 20, NULL, NULL, NULL, NULL, 'Vandal RGX'),
(, 14, 20, NULL, NULL, NULL, NULL, 'Vandal Magepunk'),
(, 15, 20, NULL, NULL, NULL, NULL, 'Marshall Elderflame'),
(, 15, 20, NULL, NULL, NULL, NULL, 'Marshall Convex'),
(, 15, 20, NULL, NULL, NULL, NULL, 'Marshall Champion 2021'),
(, 16, 20, NULL, NULL, NULL, NULL, 'Operator Champion 2022'),
(, 16, 20, NULL, NULL, NULL, NULL, 'Operator Champion 2023'),
(, 16, 20, NULL, NULL, NULL, NULL, 'Operator Champion 2024'),
(, 17, 20, NULL, NULL, NULL, NULL, 'Ares Kuronami'),
(, 17, 20, NULL, NULL, NULL, NULL, 'Ares Ion'),
(, 17, 20, NULL, NULL, NULL, NULL, 'Ares Oni'),
(, 18, 20, NULL, NULL, NULL, NULL, 'Odin Glitchpop'),
(, 18, 20, NULL, NULL, NULL, NULL, 'Odin Prime'),
(, 18, 20, NULL, NULL, NULL, NULL, 'Odin Spectrum');

INSERT INTO images (image_path, skin_id) VALUES
                                             ('', )