INSERT INTO types (name_type)
VALUES ('Couteau'),
       ('Arme de poing'),
       ('Pistolet mitrailleur'),
       ('Fusil assault'),
       ('Fusil à pompe'),
       ('Mitrailleuse'),
       ('Fusil de precision');

#insertion des nom darmes
INSERT INTO armes (name_arme, description_arme, fire_rate, damage_per_bullet, reload_speed, penetration, id_type)
VALUES ('Knife', 'couteau de combat et arme de corps à corps', 1, 75, 0, 0, 1),
       ('Classic', 'arme de poing semi-automatique', 6.75, 26, 1.75, 1, 2),
       ('Shorty', 'fusil à double canon juxtaposés', 3.33, 12, 1.75, 1, 5),
       ('Frenzy', 'arme de poing automatique', 10, 26, 1.5, 1, 3),
       ('Ghost', 'arme de poing avec silencieux', 6.75, 30, 1.5, 2, 2),
       ('Sheriff', 'revolver', 4, 55, 2.25, 3, 2),
       ('Stinger', 'pistolet mitrailleur', 16, 27, 2.25, 1, 3),
       ('Spectre', 'pistolet mitrailleur avec silencieux', 13.13, 26, 2.25, 2, 4),
       ('Bucky', 'fusil à pompe', 1.1, 20, 2.5, 1, 5),
       ('Judge', 'fusil à pompe automatique', 3.5, 17, 2.2, 2, 5),
       ('Bulldog', "fusil d'assaut bullpup", 9.14, 35, 2.5, 2, 4),
       ('Guardian', "fusil d'assaut semi automatique", 5.25, 65, 2.5, 3, 4),
       ('Phantom', "fusil d'assaut automatique avec silencieux", 11, 39, 2.5, 2, 4),
       ('Vandal', "fusil d'assaut automatique", 9.75, 40, 2.5, 2, 4),
       ('Marshall', 'carabine à levier avec lunette', 1.5, 101, 2.5, 2, 7),
       ('Operator', 'fusil de precision a verrou', 0.6, 150, 3.7, 3, 7),
       ('Ares', 'mitrailleuse', 13, 30, 3.25, 3, 6),
       ('Odin', 'mitrailleuse lourde', 15.6, 38, 5.13, 3, 6);


#insertion des variantes
INSERT INTO variantes (name_variante, id_couleur)
VALUES ('kuronami_base', 1),
       ('kuronami_black', 9),
       ('kuronami_purple', 5),
       ('kuronami_white', 4),
       ('ion_base', 4),
       ('ion_blue', 1),
       ('ion_green', 2),
       ('ion_orange', 3),
       ('oni_base', 6),
       ('oni_black', 9),
       ('oni_green', 2),
       ('oni_white', 4),
       ('glitchpop_base', 7),
       ('glitchpop_blue', 1),
       ('glitchpop_gold', 10),
       ('glitchpop_red', 6),
       ('prime_base', 4),
       ('prime_blue', 1),
       ('prime_orange', 3),
       ('prime_yellow', 8),
       ('prime2_base', 4),
       ('prime2_blue', 1),
       ('prime2_gold', 10),
       ('prime2_red', 6),
       ('spectrum_base', 4),
       ('spectrum_black', 9),
       ('spectrum_purple', 5),
       ('spectrum_red', 6),
       ('sotl_base', 9),
       ('sotl_purple', 5),
       ('sotl_pink', 7),
       ('sotl_green', 2),
       ('ptc_base', 9),
       ('ptc_blue', 1),
       ('ptc_green', 2),
       ('ptc_white', 4),
       ('gaia_base', 4),
       ('gaia_blue', 1),
       ('gaia_green', 2),
       ('gaia_red', 6),
       ('reaver_base', 5),
       ('reaver_black', 9),
       ('reaver_red', 6),
       ('reaver_white', 4),
       ('res_base', 1),
       ('res_red', 6),
       ('res_purple', 5),
       ('arcane_base', 10),
       ('rgx_base', 2),
       ('rgx_blue', 1),
       ('rgx_red', 6),
       ('rgx_yellow', 8),
       ('magepunk_base', 1),
       ('magepunk_green', 2),
       ('magepunk_purple', 5),
       ('magepunk_yellow', 8),
       ('elderflame_base', 7),
       ('elderflame_black', 9),
       ('elderflame_blue', 1),
       ('elderflame_red', 6),
       ('convex_base', 2),
       ('champion21_base', 10),
       ('champion22_base', 10),
       ('champion23_base', 10);

#insertion des couleurs
INSERT INTO couleurs (name_couleur, hexa)
VALUES ('blue', '#0000FF'),
       ('green', '#008000'),
       ('orange', '#FFA500'),
       ('white', '#FFFFFF'),
       ('purple', '#800080'),
       ('red', '#FF0000'),
       ('pink', '#FFC0CB'),
       ('yellow', '#FFFF00'),
       ('black', '#000000'),
       ('gold', '#FFD700'),
       ('special', '#FFFFFF00');

INSERT INTO collections_variantes (id_collection, id_variante)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (2, 5),
       (2, 6),
       (2, 7),
       (2, 8),
       (3, 9),
       (3, 10),
       (3, 11),
       (3, 12),
       (4, 13),
       (4, 14),
       (4, 15),
       (4, 16),
       (5, 17),
       (5, 18),
       (5, 19),
       (5, 20),
       (6, 21),
       (6, 22),
       (6, 23),
       (6, 24),
       (7, 25),
       (7, 26),
       (7, 27),
       (7, 28),
       (8, 29),
       (8, 30),
       (8, 31),
       (8, 32),
       (9, 33),
       (9, 34),
       (9, 35),
       (9, 36),
       (10, 37),
       (10, 38),
       (10, 39),
       (10, 40),
       (11, 41),
       (11, 42),
       (11, 43),
       (11, 44),
       (12, 45),
       (12, 46),
       (12, 47),
       (13, 48),
       (14, 49),
       (14, 50),
       (14, 51),
       (14, 52),
       (15, 53),
       (15, 54),
       (15, 55),
       (15, 56),
       (16, 57),
       (16, 58),
       (16, 59),
       (16, 60),
       (17, 61),
       (18, 62),
       (18, 63),
       (18, 64);

INSERT INTO armes_skins (id_arme, id_skin)
VALUES (1, 1),
       (1, 2),
       (1, 3),
       (1, 4),
       (2, 5),
       (2, 6),
       (2, 7),
       (2, 8),
       (3, 9),
       (3, 10),
       (3, 11),
       (3, 12),
       (4, 13),
       (4, 14),
       (4, 15),
       (4, 16),
       (5, 17),
       (5, 18),
       (5, 19),
       (5, 20),
       (6, 21),
       (6, 22),
       (6, 23),
       (6, 24),
       (7, 25),
       (7, 26),
       (7, 27),
       (7, 28),
       (8, 29),
       (8, 30),
       (8, 31),
       (8, 32),
       (9, 33),
       (9, 34),
       (9, 35),
       (9, 36),
       (10, 37),
       (10, 38),
       (10, 39),
       (10, 40),
       (11, 41),
       (11, 42),
       (11, 43),
       (11, 44),
       (12, 45),
       (12, 46),
       (12, 47),
       (13, 48),
       (14, 49),
       (14, 50),
       (14, 51),
       (14, 52),
       (15, 53),
       (15, 54),
       (15, 55),
       (15, 56),
       (16, 57),
       (16, 58),
       (16, 59),
       (16, 60),
       (17, 61),
       (18, 62),
       (18, 63),
       (18, 64);

#insertion des differents skins
INSERT INTO skins (name_skin, prix, reduction, description_skin, rarete, id_variante)
VALUES  ('Kuronami Knife', 2000, NULL, 'couteau de la collection Kuronami - base', 1, 1),
        ('Kuronami Knife', 2000, NULL, 'couteau de la collection Kuronami - black', 1, 1),
        ('Kuronami Knife', 2000, NULL, 'couteau de la collection Kuronami - purple', 1, 1),
        ('Kuronami Knife', 2000, NULL, 'couteau de la collection Kuronami - white', 1, 1),
        ('Ion Knife', 2000, NULL, 'Gantelet de la collection Ion - base', 1, 2),
        ('Ion Knife', 2000, NULL, 'Gantelet de la collection Ion - blue', 1, 2),
        ('Ion Knife', 2000, NULL, 'Gantelet de la collection Ion - green', 1, 2),
        ('Ion Knife', 2000, NULL, 'Gantelet de la collection Ion - orange', 1, 2),
        ('Oni Knife', 2000, NULL, 'Katana de la collection Oni - base', 1, 3),
        ('Oni Knife', 2000, NULL, 'Katana de la collection Oni - black', 1, 3),
        ('Oni Knife', 2000, NULL, 'Katana de la collection Oni - green', 1, 3),
        ('Oni Knife', 2000, NULL, 'Katana de la collection Oni - white', 1, 3),
        ('Glitchpop Classic', 2000, NULL, 'Classic de la collection Glitchpop - base', 2, 4),
        ('Glitchpop Classic', 2000, NULL, 'Classic de la collection Glitchpop - blue', 2, 4),
        ('Glitchpop Classic', 2000, NULL, 'Classic de la collection Glitchpop - gold', 2, 4),
        ('Glitchpop Classic', 2000, NULL, 'Classic de la collection Glitchpop - red', 2, 4),
        ('Prime Classic', 2000, NULL, 'Classic de la collection Prime - base', 2, 5),
        ('Prime Classic', 2000, NULL, 'Classic de la collection Prime - blue', 2, 5),
        ('Prime Classic', 2000, NULL, 'Classic de la collection Prime - gold', 2, 5),
        ('Prime Classic', 2000, NULL, 'Classic de la collection Prime - red', 2, 5),
        ('Spectrum Classis', 2000, NULL, 'Classic de la collection Spectrum - base', 2, 6),
        ('Spectrum Classis', 2000, NULL, 'Classic de la collection Spectrum - black', 2, 6),
        ('Spectrum Classis', 2000, NULL, 'Classic de la collection Spectrum - purple', 2, 6),
        ('Spectrum Classis', 2000, NULL, 'Classic de la collection Spectrum - red', 2, 6),
        ('Oni Shorty', 2000, NULL, 'Shorty de la collection Oni - base', 3, 3),
        ('Oni Shorty', 2000, NULL, 'Shorty de la collection Oni - black', 3, 3),
        ('Oni Shorty', 2000, NULL, 'Shorty de la collection Oni - green', 3, 3),
        ('Oni Shorty', 2000, NULL, 'Shorty de la collection Oni - white', 3, 3),
        ('SOTL Shorty', 2000, NULL, 'Shorty de la collection Sentinels of the light - base', 3, 7),
        ('SOTL Shorty', 2000, NULL, 'Shorty de la collection Sentinels of the light - purple', 3, 7),
        ('SOTL Shorty', 2000, NULL, 'Shorty de la collection Sentinels of the light - pink', 3, 7),
        ('SOTL Shorty', 2000, NULL, 'Shorty de la collection Sentinels of the light - green', 3, 7),
        ('PTC Shorty', 2000, NULL, 'Shorty de la collection Prelude to Chaos - base', 3, 8),
        ('PTC Shorty', 2000, NULL, 'Shorty de la collection Prelude to Chaos - blue', 3, 8),
        ('PTC Shorty', 2000, NULL, 'Shorty de la collection Prelude to Chaos - green', 3, 8),
        ('PTC Shorty', 2000, NULL, 'Shorty de la collection Prelude to Chaos - white', 3, 8),
        ('Prime Frenzy', 2000, NULL, 'Frenzy de la collection Prime//2.0 - base', 4, 5),
        ('Prime Frenzy', 2000, NULL, 'Frenzy de la collection Prime//2.0 - blue', 4, 5),
        ('Prime Frenzy', 2000, NULL, 'Frenzy de la collection Prime//2.0 - gold', 4, 5),
        ('Prime Frenzy', 2000, NULL, 'Frenzy de la collection Prime//2.0 - red', 4, 5),
        ('Glitchpop Frenzy', 2000, NULL, 'Frenzy de la collection Glitchpop - base', 4, 4),
        ('Glitchpop Frenzy', 2000, NULL, 'Frenzy de la collection Glitchpop - blue', 4, 4),
        ('Glitchpop Frenzy', 2000, NULL, 'Frenzy de la collection Glitchpop - gold', 4, 4),
        ('Glitchpop Frenzy', 2000, NULL, 'Frenzy de la collection Glitchpop - red', 4, 4),
        ('Ion Frenzy', 2000, NULL, 'Frenzy de la collection Ion - base', 4, 2),
        ('Ion Frenzy', 2000, NULL, 'Frenzy de la collection Ion - blue', 4, 2),
        ('Ion Frenzy', 2000, NULL, 'Frenzy de la collection Ion - green', 4, 2),
        ('Ion Frenzy', 2000, NULL, 'Frenzy de la collection Ion - orange', 4, 2),
        ('Gaia Ghost', 2000, NULL, 'Ghost de la collection Gaia s vengeance - base', 5, 9),
        ('Gaia Ghost', 2000, NULL, 'Ghost de la collection Gaia s vengeance - blue', 5, 9),
        ('Gaia Ghost', 2000, NULL, 'Ghost de la collection Gaia s vengeance - green', 5, 9),
        ('Gaia Ghost', 2000, NULL, 'Ghost de la collection Gaia s vengeance - red', 5, 9),
        ('Reaver Ghost', 2000, NULL, 'Ghost de la collection Reaver - base', 5, 10),
        ('Reaver Ghost', 2000, NULL, 'Ghost de la collection Reaver - black', 5, 10),
        ('Reaver Ghost', 2000, NULL, 'Ghost de la collection Reaver - red', 5, 10),
        ('Reaver Ghost', 2000, NULL, 'Ghost de la collection Reaver - white', 5, 10),
        ('RES Ghost', 2000, NULL, 'Ghost de la collection Radiant Entertainment System - base', 5, 11),
        ('RES Ghost', 2000, NULL, 'Ghost de la collection Radiant Entertainment System - red', 5, 11),
        ('RES Ghost', 2000, NULL, 'Ghost de la collection Radiant Entertainment System - purple', 5, 11),
        ('Arcane Sheriff', 2000, NULL, 'Sheriff de l edition limitee Arcane - base', 6, 12),
        ('Ion Sheriff', 2000, NULL, 'Sheriff de la collection Ion - base', 6, 2),
        ('Ion Sheriff', 2000, NULL, 'Sheriff de la collection Ion - blue', 6, 2),
        ('Ion Sheriff', 2000, NULL, 'Sheriff de la collection Ion - green', 6, 2),
        ('Ion Sheriff', 2000, NULL, 'Sheriff de la collection Ion - orange', 6, 2),
        ('Reaver Sheriff', 2000, NULL, 'Sheriff de la collection Reaver - base', 6, 10),
        ('Reaver Sheriff', 2000, NULL, 'Sheriff de la collection Reaver - black', 6, 10),
        ('Reaver Sheriff', 2000, NULL, 'Sheriff de la collection Reaver - red', 6, 10),
        ('Reaver Sheriff', 2000, NULL, 'Sheriff de la collection Reaver - white', 6, 10),
        ('SOTL Sherill', 2000, NULL, 'Sheriff de la collection Sentinel of the Light - base', 6, 7),
        ('SOTL Sherill', 2000, NULL, 'Sheriff de la collection Sentinel of the Light - purple', 6, 7),
        ('SOTL Sherill', 2000, NULL, 'Sheriff de la collection Sentinel of the Light - pink', 6, 7),
        ('SOTL Sherill', 2000, NULL, 'Sheriff de la collection Sentinel of the Light - green', 6, 7),
        ('PTC Stinger', 2000, NULL, 'Stinger de la collection Prelude to Chaos - base', 7, 8),
        ('PTC Stinger', 2000, NULL, 'Stinger de la collection Prelude to Chaos - blue', 7, 8),
        ('PTC Stinger', 2000, NULL, 'Stinger de la collection Prelude to Chaos - green', 7, 8),
        ('PTC Stinger', 2000, NULL, 'Stinger de la collection Prelude to Chaos - white', 7, 8),
        ('RGX Stinger', 2000, NULL, 'Stinger de la collection RGX - base', 7, 13),
        ('RGX Stinger', 2000, NULL, 'Stinger de la collection RGX - blue', 7, 13),
        ('RGX Stinger', 2000, NULL, 'Stinger de la collection RGX - red', 7, 13),
        ('RGX Stinger', 2000, NULL, 'Stinger de la collection RGX - yellow', 7, 13),
        ('Reaver Spectre', 2000, NULL, 'Spectre de la collection Reaver - base', 8, 10),
        ('Reaver Spectre', 2000, NULL, 'Spectre de la collection Reaver - black', 8, 10),
        ('Reaver Spectre', 2000, NULL, 'Spectre de la collection Reaver - red', 8, 10),
        ('Reaver Spectre', 2000, NULL, 'Spectre de la collection Reaver - white', 8, 10),
        ('Magepunk Spectre', 2000, NULL, 'Spectre de la collection MagePunk - base', 8, 14),
        ('Magepunk Spectre', 2000, NULL, 'Spectre de la collection MagePunk - green', 8, 14),
        ('Magepunk Spectre', 2000, NULL, 'Spectre de la collection MagePunk - purple', 8, 14),
        ('Magepunk Spectre', 2000, NULL, 'Spectre de la collection MagePunk - yellow', 8, 14),
        ('Kuronami Spectre', 2000, NULL, 'Spectre de la collection Kuronami - base', 8, 1),
        ('Kuronami Spectre', 2000, NULL, 'Spectre de la collection Kuronami - black', 8, 1),
        ('Kuronami Spectre', 2000, NULL, 'Spectre de la collection Kuronami - purple', 8, 1),
        ('Kuronami Spectre', 2000, NULL, 'Spectre de la collection Kuronami - white', 8, 1),
        ('Prime Spectre', 2000, NULL, 'Spectre de la collection Prime - base', 8, 5),
        ('Prime Spectre', 2000, NULL, 'Spectre de la collection Prime - blue', 8, 5),
        ('Prime Spectre', 2000, NULL, 'Spectre de la collection Prime - orange', 8, 5),
        ('Prime Spectre', 2000, NULL, 'Spectre de la collection Prime - yellow', 8, 5),
        ('Oni Bucky', 2000, NULL, 'Bucky de la collection Oni - base', 9, 3),
        ('Oni Bucky', 2000, NULL, 'Bucky de la collection Oni - black', 9, 3),
        ('Oni Bucky', 2000, NULL, 'Bucky de la collection Oni - green', 9, 3),
        ('Oni Bucky', 2000, NULL, 'Bucky de la collection Oni - white', 9, 3),
        ('Gaia Bucky', 2000, NULL, 'Bucky de la collection Gaia s vengeance - base', 9, 9),
        ('Gaia Bucky', 2000, NULL, 'Bucky de la collection Gaia s vengeance - blue', 9, 9),
        ('Gaia Bucky', 2000, NULL, 'Bucky de la collection Gaia s vengeance - green', 9, 9),
        ('Gaia Bucky', 2000, NULL, 'Bucky de la collection Gaia s vengeance - red', 9, 9),
        ('Prime Bucky', 2000, NULL, 'Bucky de la collection Prime - base', 9, 5),
        ('Prime Bucky', 2000, NULL, 'Bucky de la collection Prime - blue', 9, 5),
        ('Prime Bucky', 2000, NULL, 'Bucky de la collection Prime - orange', 9, 5),
        ('Prime Bucky', 2000, NULL, 'Bucky de la collection Prime - yellow', 9, 5),
        ('Glitchpop Judge', 2000, NULL, 'Judge de la collection Glitchpop - base', 10, 4),
        ('Glitchpop Judge', 2000, NULL, 'Judge de la collection Glitchpop - blue', 10, 4),
        ('Glitchpop Judge', 2000, NULL, 'Judge de la collection Glitchpop - gold', 10, 4),
        ('Glitchpop Judge', 2000, NULL, 'Judge de la collection Glitchpop - red', 10, 4),
        ('Elderflame Judge', 2000, NULL, 'Judge de la collection Elderflame - base', 10, 15),
        ('Elderflame Judge', 2000, NULL, 'Judge de la collection Elderflame - black', 10, 15),
        ('Elderflame Judge', 2000, NULL, 'Judge de la collection Elderflame - blue', 10, 15),
        ('Elderflame Judge', 2000, NULL, 'Judge de la collection Elderflame - red', 10, 15),
        ('Convex Judge', 2000, NULL, 'Judge de la collection Convex - base', 10, 16),
        ('RES Bulldog', 2000, NULL, 'Bulldog de la collection Radiant Entertainment System - base', 11, 11),
        ('RES Bulldog', 2000, NULL, 'Bulldog de la collection Radiant Entertainment System - red', 11, 11),
        ('RES Bulldog', 2000, NULL, 'Bulldog de la collection Radiant Entertainment System - purple', 11, 11),
        ('Oni Bulldog', 2000, NULL, 'Bulldog de la collection Oni - base', 11, 3),
        ('Oni Bulldog', 2000, NULL, 'Bulldog de la collection Oni - black', 11, 3),
        ('Oni Bulldog', 2000, NULL, 'Bulldog de la collection Oni - green', 11, 3),
        ('Oni Bulldog', 2000, NULL, 'Bulldog de la collection Oni - white', 11, 3),
        ('Spectrum Bulldog', 2000, NULL, 'Bulldog de la collection Spectrum - base', 11, 6),
        ('Spectrum Bulldog', 2000, NULL, 'Bulldog de la collection Spectrum - black', 11, 6),
        ('Spectrum Bulldog', 2000, NULL, 'Bulldog de la collection Spectrum - purple', 11, 6),
        ('Spectrum Bulldog', 2000, NULL, 'Bulldog de la collection Spectrum - red', 11, 6),
        ('Gaia Guardian', 2000, NULL, 'Guardian de la collection Gaia s vengeance - base', 12, 9),
        ('Gaia Guardian', 2000, NULL, 'Guardian de la collection Gaia s vengeance - blue', 12, 9),
        ('Gaia Guardian', 2000, NULL, 'Guardian de la collection Gaia s vengeance - green', 12, 9),
        ('Gaia Guardian', 2000, NULL, 'Guardian de la collection Gaia s vengeance - red', 12, 9),
        ('Prime Guardian', 2000, NULL, 'Guardian de la collection Prime - base', 12, 5),
        ('Prime Guardian', 2000, NULL, 'Guardian de la collection Prime - blue', 12, 5),
        ('Prime Guardian', 2000, NULL, 'Guardian de la collection Prime - orange', 12, 5),
        ('Prime Guardian', 2000, NULL, 'Guardian de la collection Prime - yellow', 12, 5),
        ('Reaver Guardian', 2000, NULL, 'Guardian de la collection Reaver - base', 12, 10),
        ('Reaver Guardian', 2000, NULL, 'Guardian de la collection Reaver - black', 12, 10),
        ('Reaver Guardian', 2000, NULL, 'Guardian de la collection Reaver - red', 12, 10),
        ('Reaver Guardian', 2000, NULL, 'Guardian de la collection Reaver - white', 12, 10),
        ('Champion22 Phantom', 2000, NULL, 'Phantom de la collection Champion 22', 13, 17),
        ('Glitchpop Phantom', 2000, NULL, 'Phantom de la collection Glitchpop - base', 13, 4),
        ('Glitchpop Phantom', 2000, NULL, 'Phantom de la collection Glitchpop - blue', 13, 4),
        ('Glitchpop Phantom', 2000, NULL, 'Phantom de la collection Glitchpop - gold', 13, 4),
        ('Glitchpop Phantom', 2000, NULL, 'Phantom de la collection Glitchpop - red', 13, 4),
        ('Prime Phantom', 2000, NULL, 'Phantom de la collection Prime - base', 13, 5),
        ('Prime Phantom', 2000, NULL, 'Phantom de la collection Prime - blue', 13, 5),
        ('Prime Phantom', 2000, NULL, 'Phantom de la collection Prime - orange', 13, 5),
        ('Prime Phantom', 2000, NULL, 'Phantom de la collection Prime - yellow', 13, 5),
        ('Oni Phantom', 2000, NULL, 'Phantom de la collection Oni - base', 13, 3),
        ('Oni Phantom', 2000, NULL, 'Phantom de la collection Oni - black', 13, 3),
        ('Oni Phantom', 2000, NULL, 'Phantom de la collection Oni - green', 13, 3),
        ('Oni Phantom', 2000, NULL, 'Phantom de la collection Oni - white', 13, 3),
        ('RES Phantom', 2000, NULL, 'Phantom de la collection Radiant Entertainment System - base', 13, 11),
        ('RES Phantom', 2000, NULL, 'Phantom de la collection Radiant Entertainment System - red', 13, 11),
        ('RES Phantom', 2000, NULL, 'Phantom de la collection Radiant Entertainment System - purple', 13, 11),
        ('Champion21 Vandal', 2000, NULL, 'Vandal de la collection Champion 21', 13, 18),
        ('Champion23 Vandal', 2000, NULL, 'Vandal de la collection Champion 23', 13, 19),
        ('Gaia Vandal', 2000, NULL, 'Vandal de la collection Gaia s vengeance - base', 13, 9),
        ('Gaia Vandal', 2000, NULL, 'Vandal de la collection Gaia s vengeance - blue', 13, 9),
        ('Gaia Vandal', 2000, NULL, 'Vandal de la collection Gaia s vengeance - green', 13, 9),
        ('Gaia Vandal', 2000, NULL, 'Vandal de la collection Gaia s vengeance - red', 13, 9),
        ('Ion Vandal', 2000, NULL, 'Vandal de la collection Ion - base', 13, 2),
        ('Ion Vandal', 2000, NULL, 'Vandal de la collection Ion - blue', 13, 2),
        ('Ion Vandal', 2000, NULL, 'Vandal de la collection Ion - green', 13, 2),
        ('Ion Vandal', 2000, NULL, 'Vandal de la collection Ion - red', 13, 2),
        ('Magepunk Vandal', 2000, NULL, 'Vandal de la collection Magepunk - base', 13, 14),
        ('Magepunk Vandal', 2000, NULL, 'Vandal de la collection Magepunk - green', 13, 14),
        ('Magepunk Vandal', 2000, NULL, 'Vandal de la collection Magepunk - purple', 13, 14),
        ('Magepunk Vandal', 2000, NULL, 'Vandal de la collection Magepunk - yellow', 13, 14),
        ('PTC Vandal', 2000, NULL, 'Vandal de la collection Prelude to Chaos - base', 13, 8),
        ('PTC Vandal', 2000, NULL, 'Vandal de la collection Prelude to Chaos - blue', 13, 8),
        ('PTC Vandal', 2000, NULL, 'Vandal de la collection Prelude to Chaos - green', 13, 8),
        ('PTC Vandal', 2000, NULL, 'Vandal de la collection Prelude to Chaos - white', 13, 8),
        ('Gaia Marshall', 2000, NULL, 'Marshall de la collection Gaia s vengeance - base', 14, 9),
        ('Gaia Marshall', 2000, NULL, 'Marshall de la collection Gaia s vengeance - blue', 14, 9),
        ('Gaia Marshall', 2000, NULL, 'Marshall de la collection Gaia s vengeance - green', 14, 9),
        ('Gaia Marshall', 2000, NULL, 'Marshall de la collection Gaia s vengeance - red', 14, 9),
        ('Magepunk Marshall', 2000, NULL, 'Marshall de la collection Magepunk - base', 14, 14),
        ('Magepunk Marshall', 2000, NULL, 'Marshall de la collection Magepunk - green', 14, 14),
        ('Magepunk Marshall', 2000, NULL, 'Marshall de la collection Magepunk - purple', 14, 14),
        ('Magepunk Marshall', 2000, NULL, 'Marshall de la collection Magepunk - yellow', 14, 14),
        ('Reaver Operator', 2000, NULL, 'Operator de la collection Reaver - base', 15, 10),
        ('Reaver Operator', 2000, NULL, 'Operator de la collection Reaver - black', 15, 10),
        ('Reaver Operator', 2000, NULL, 'Operator de la collection Reaver - red', 15, 10),
        ('Reaver Operator', 2000, NULL, 'Operator de la collection Reaver - white', 15, 10),
        ('Glitchpop Operator', 2000, NULL, 'Operator de la collection Glitchpop - base', 15, 4),
        ('Glitchpop Operator', 2000, NULL, 'Operator de la collection Glitchpop - blue', 15, 4),
        ('Glitchpop Operator', 2000, NULL, 'Operator de la collection Glitchpop - gold', 15, 4),
        ('Glitchpop Operator', 2000, NULL, 'Operator de la collection Glitchpop - red', 15, 4),
        ('RES Operator', 2000, NULL, 'Operator de la collection Radiant Entertainment System - base', 15, 11),
        ('RES Operator', 2000, NULL, 'Operator de la collection Radiant Entertainment System - red', 15, 11),
        ('RES Operator', 2000, NULL, 'Operator de la collection Radiant Entertainment System - purple', 15, 11),
        ('SOTL Ares', 2000, NULL, 'Ares de la collection Sentinel of the Light - base', 16, 7),
        ('SOTL Ares', 2000, NULL, 'Ares de la collection Sentinel of the Light - purple', 16, 7),
        ('SOTL Ares', 2000, NULL, 'Ares de la collection Sentinel of the Light - pink', 16, 7),
        ('SOTL Ares', 2000, NULL, 'Ares de la collection Sentinel of the Light - green', 16, 7),
        ('Ion Ares', 2000, NULL, 'Ares de la collection Ion - base', 16, 2),
        ('Ion Ares', 2000, NULL, 'Ares de la collection Ion - blue', 16, 2),
        ('Ion Ares', 2000, NULL, 'Ares de la collection Ion - green', 16, 2),
        ('Ion Ares', 2000, NULL, 'Ares de la collection Ion - orange', 16, 2),
        ('Oni Ares', 2000, NULL, 'Ares de la collection Oni - base', 16, 3),
        ('Oni Ares', 2000, NULL, 'Ares de la collection Oni - black', 16, 3),
        ('Oni Ares', 2000, NULL, 'Ares de la collection Oni - green', 16, 3),
        ('Oni Ares', 2000, NULL, 'Ares de la collection Oni - white', 16, 3),
        ('Prime Odin', 2000, NULL, 'Odin de la collection Prime - base', 17, 5),
        ('Prime Odin', 2000, NULL, 'Odin de la collection Prime - blue', 17, 5),
        ('Prime Odin', 2000, NULL, 'Odin de la collection Prime - orange', 17, 5),
        ('Prime Odin', 2000, NULL, 'Odin de la collection Prime - yellow', 17, 5),
        ('Reaver Odin', 2000, NULL, 'Odin de la collection Reaver - base', 17, 10),
        ('Reaver Odin', 2000, NULL, 'Odin de la collection Reaver - black', 17, 10),
        ('Reaver Odin', 2000, NULL, 'Odin de la collection Reaver - red', 17, 10),
        ('Reaver Odin', 2000, NULL, 'Odin de la collection Reaver - white', 17, 10),
        ('Glitchpop Odin', 2000, NULL, 'Odin de la collection Glitchpop - base', 17, 4),
        ('Glitchpop Odin', 2000, NULL, 'Odin de la collection Glitchpop - blue', 17, 4),
        ('Glitchpop Odin', 2000, NULL, 'Odin de la collection Glitchpop - gold', 17, 4),
        ('Glitchpop Odin', 2000, NULL, 'Odin de la collection Glitchpop - red', 17, 4);

#insertion des differentes collection de la table collection
INSERT INTO collections (name_collection)
VALUES ('Kuronami'),
       ('Ion'),
       ('Oni'),
       ('Glitchpop'),
       ('Prime'),
       ('Prime//2.0'),
       ('Spectrum'),
       ('Sentinel of the light'),
       ('Prelude to Chaos'),
       ("Gaia's vengance"),
       ('Reaver'),
       ('Radiant Entertainment System'),
       ('Arcane'),
       ('RGX'),
       ('Magepunk'),
       ('Elderflame'),
       ('Convex'),
       ('Champion 2021'),
       ('Champion 2022'),
       ('Champion 2023');

#insertion des images
INSERT INTO images (path, alt, id_skin)
VALUES ('/knife/kuronami/kuronami_knife_base/base.png', 'couteau de la collection Kuronami - base', 1),
('/knife/kuronami/kuronami_knife_black/base.png', 'couteau de la collection Kuronami - black', 2),
('/knife/kuronami/kuronami_knife_purple/base.png', 'couteau de la collection Kuronami - purple', 3),
('/knife/kuronami/kuronami_knife_white/base.png', 'couteau de la collection Kuronami - white', 4),
('/knife/ion/ion_knife_base/base.png', 'Gantelet de la collection Ion - base', 5),
('/knife/ion/ion_knife_blue/base.png', 'Gantelet de la collection Ion - blue', 6),
('/knife/ion/ion_knife_green/base.png', 'Gantelet de la collection Ion - green', 7),
('/knife/ion/ion_knife_orange/base.png', 'Gantelet de la collection Ion - orange', 8),
('/knife/oni/oni_knife_base/base.png', 'Katana de la collection Oni - base', 9),
('/knife/oni/oni_knife_black/base.png', 'Katana de la collection Oni - black', 10),
('/knife/oni/oni_knife_green/base.png', 'Katana de la collection Oni - green', 11),
('/knife/oni/oni_knife_white/base.png', 'Katana de la collection Oni - white', 12),
('/classic/glitchpop/glitchpop_classic_base/base.png', 'Classic de la collection Glitchpop - base', 13),
('/classic/glitchpop/glitchpop_classic_blue/base.png', 'Classic de la collection Glitchpop - blue', 14),
('/classic/glitchpop/glitchpop_classic_gold/base.png', 'Classic de la collection Glitchpop - gold', 15),
('/classic/glitchpop/glitchpop_classic_red/base.png', 'Classic de la collection Glitchpop - red', 16),
('/classic/prime/prime_classic_base/base.png', 'Classic de la collection Prime - base', 17),
('/classic/prime/prime_classic_blue/base.png', 'Classic de la collection Prime - blue', 18),
('/classic/prime/prime_classic_gold/base.png', 'Classic de la collection Prime - gold', 19),
('/classic/prime/prime_classic_red/base.png', 'Classic de la collection Prime - red', 20),
('/classic/spectrum/spectrum_classic_base/base.png', 'Classic de la collection Spectrum - base', 21),
('/classic/spectrum/spectrum_classic_black/base.png', 'Classic de la collection Spectrum - black', 22),
('/classic/spectrum/spectrum_classic_purple/base.png', 'Classic de la collection Spectrum - purple', 23),
('/classic/spectrum/spectrum_classic_red/base.png', 'Classic de la collection Spectrum - red', 24),
('/shorty/oni/oni_shorty_base/base.png', 'Shorty de la collection Oni - base', 25),
('/shorty/oni/oni_shorty_black/base.png', 'Shorty de la collection Oni - black', 26),
('/shorty/oni/oni_shorty_green/base.png', 'Shorty de la collection Oni - green', 27),
('/shorty/oni/oni_shorty_white/base.png', 'Shorty de la collection Oni - white', 28),
('/shorty/sotl/sotl_shorty_base/base.png', 'Shorty de la collection Sentinels of the light - base', 29),
('/shorty/sotl/sotl_shorty_purple/base.png', 'Shorty de la collection Sentinels of the light - purple', 30),
('/shorty/sotl/sotl_shorty_pink/base.png', 'Shorty de la collection Sentinels of the light - pink', 31),
('/shorty/sotl/sotl_shorty_green/base.png', 'Shorty de la collection Sentinels of the light - green', 32),
('/shorty/ptc/ptc_shorty_base/base.png', 'Shorty de la collection Prelude to Chaos - base', 33),
('/shorty/ptc/ptc_shorty_blue/base.png', 'Shorty de la collection Prelude to Chaos - blue', 34),
('/shorty/ptc/ptc_shorty_green/base.png', 'Shorty de la collection Prelude to Chaos - green', 35),
('/shorty/ptc/ptc_shorty_white/base.png', 'Shorty de la collection Prelude to Chaos - white', 36),
('/frenzy/prime/prime_frenzy_base/base.png', 'Frenzy de la collection Prime//2.0 - base', 37),
('/frenzy/prime/prime_frenzy_blue/base.png', 'Frenzy de la collection Prime//2.0 - blue', 38),
('/frenzy/prime/prime_frenzy_gold/base.png', 'Frenzy de la collection Prime//2.0 - gold', 39),
('/frenzy/prime/prime_frenzy_red/base.png', 'Frenzy de la collection Prime//2.0 - red', 40),
('/frenzy/glitchpop/glitchpop_frenzy_base/base.png', 'Frenzy de la collection Glitchpop - base', 41),
('/frenzy/glitchpop/glitchpop_frenzy_blue/base.png', 'Frenzy de la collection Glitchpop - blue', 42),
('/frenzy/glitchpop/glitchpop_frenzy_gold/base.png', 'Frenzy de la collection Glitchpop - gold', 43),
('/frenzy/glitchpop/glitchpop_frenzy_red/base.png', 'Frenzy de la collection Glitchpop - red', 44),
('/frenzy/ion/ion_frenzy_base/base.png', 'Frenzy de la collection Ion - base', 45),
('/frenzy/ion/ion_frenzy_blue/base.png', 'Frenzy de la collection Ion - blue', 46),
('/frenzy/ion/ion_frenzy_green/base.png', 'Frenzy de la collection Ion - green', 47),
('/frenzy/ion/ion_frenzy_orange/base.png', 'Frenzy de la collection Ion - orange', 48),
('/ghost/gaia/gaia_ghost_base/base.png', 'Ghost de la collection Gaia s vengeance - base', 49),
('/ghost/gaia/gaia_ghost_blue/base.png', 'Ghost de la collection Gaia s vengeance - blue', 50),
('/ghost/gaia/gaia_ghost_green/base.png', 'Ghost de la collection Gaia s vengeance - green', 51),
('/ghost/gaia/gaia_ghost_red/base.png', 'Ghost de la collection Gaia s vengeance - red', 52),
('/ghost/reaver/reaver_ghost_base/base.png', 'Ghost de la collection Reaver - base', 53),
('/ghost/reaver/reaver_ghost_black/base.png', 'Ghost de la collection Reaver - black', 54),
('/ghost/reaver/reaver_ghost_red/base.png', 'Ghost de la collection Reaver - red', 55),
('/ghost/reaver/reaver_ghost_white/base.png', 'Ghost de la collection Reaver - white', 56),
('/ghost/res/res_ghost_base/base.png', 'Ghost de la collection Radiant Entertainment System', 57),
('/ghost/res/res_ghost_purple/base.png', 'Ghost de la collection Radiant Entertainment System', 58),
('/ghost/res/res_ghost_red/base.png', 'Ghost de la collection Radiant Entertainment System', 59),
('/sheriff/arcane/arcane_sheriff_base/base.png', 'Sheriff de l edition limitee Arcane', 60),
('/sheriff/reaver/reaver_sheriff_base/base.png', 'Sheriff de la collection Reaver', 61),
('/sheriff/reaver/reaver_sheriff_black/base.png', 'Sheriff de la collection Reaver', 62),
('/sheriff/reaver/reaver_sheriff_red/base.png', 'Sheriff de la collection Reaver', 63),
('/sheriff/reaver/reaver_sheriff_white/base.png', 'Sheriff de la collection Reaver', 64),
('/sheriff/sotl/sotl_sheriff_base/base.png', 'Sheriff de la collection Sentinel of the Light', 65),
('/sheriff/sotl/sotl_sheriff_green/base.png', 'Sheriff de la collection Sentinel of the Light', 66),
('/sheriff/sotl/sotl_sheriff_pink/base.png', 'Sheriff de la collection Sentinel of the Light', 67),
('/sheriff/sotl/sotl_sheriff_purple/base.png', 'Sheriff de la collection Sentinel of the Light', 68),
('/stinger/ptc/ptc_stinger_base/base.png', 'Stinger de la collection Prelude to Chaos', 69),
('/stinger/ptc/ptc_stinger_blue/base.png', 'Stinger de la collection Prelude to Chaos', 70),
('/stinger/ptc/ptc_stinger_green/base.png', 'Stinger de la collection Prelude to Chaos', 71),
('/stinger/ptc/ptc_stinger_white/base.png', 'Stinger de la collection Prelude to Chaos', 72),
('/stinger/rgx/rgx_stinger_base/base.png', 'Stinger de la collection RGX11Z', 73),
('/stinger/rgx/rgx_stinger_blue/base.png', 'Stinger de la collection RGX11Z', 74),
('/stinger/rgx/rgx_stinger_red/base.png', 'Stinger de la collection RGX11Z', 75),
('/stinger/rgx/rgx_stinger_yellow/base.png', 'Stinger de la collection RGX11Z', 76),
('/stinger/regen/regen_stinger_base/base.png', 'Stinger de la collection Reaver', 77),
('/stinger/regen/regen_stinger_black/base.png', 'Stinger de la collection Reaver', 78),
('/stinger/regen/regen_stinger_red/base.png', 'Stinger de la collection Reaver', 79),
('/stinger/regen/regen_stinger_white/base.png', 'Stinger de la collection Reaver', 80),
('/stinger/spectrum/spectrum_stinger_base/base.png', 'Stinger de la collection Spectrum', 81),
('/stinger/spectrum/spectrum_stinger_black/base.png', 'Stinger de la collection Spectrum', 82),
('/stinger/spectrum/spectrum_stinger_purple/base.png', 'Stinger de la collection Spectrum', 83),
('/stinger/spectrum/spectrum_stinger_red/base.png', 'Stinger de la collection Spectrum', 84),
('/bulldog/glitchpop/glitchpop_bulldog_base/base.png', 'Bulldog de la collection Glitchpop', 85),
('/bulldog/glitchpop/glitchpop_bulldog_blue/base.png', 'Bulldog de la collection Glitchpop', 86),
('/bulldog/glitchpop/glitchpop_bulldog_gold/base.png', 'Bulldog de la collection Glitchpop', 87),
('/bulldog/glitchpop/glitchpop_bulldog_red/base.png', 'Bulldog de la collection Glitchpop', 88),
('/bulldog/magepunk/magepunk_bulldog_base/base.png', 'Bulldog de la collection Magepunk', 89),
('/bulldog/magepunk/magepunk_bulldog_green/base.png', 'Bulldog de la collection Magepunk', 90),
('/bulldog/magepunk/magepunk_bulldog_orange/base.png', 'Bulldog de la collection Magepunk', 91),
('/bulldog/magepunk/magepunk_bulldog_purple/base.png', 'Bulldog de la collection Magepunk', 92),
('/guardian/gaia/gaia_guardian_base/base.png', 'Guardian de la collection Gaia s vengeance', 93),
('/guardian/gaia/gaia_guardian_blue/base.png', 'Guardian de la collection Gaia s vengeance', 94),
('/guardian/gaia/gaia_guardian_green/base.png', 'Guardian de la collection Gaia s vengeance', 95),
('/guardian/gaia/gaia_guardian_red/base.png', 'Guardian de la collection Gaia s vengeance', 96),
('/guardian/protocol/protocol_guardian_base/base.png', 'Guardian de la collection Protocol', 97),
('/guardian/protocol/protocol_guardian_blue/base.png', 'Guardian de la collection Protocol', 98),
('/guardian/protocol/protocol_guardian_orange/base.png', 'Guardian de la collection Protocol', 99),
('/guardian/protocol/protocol_guardian_red/base.png', 'Guardian de la collection Protocol', 100),
('/vandal/chronovoid/chronovoid_vandal_base/base.png', 'Vandal de la collection Chronovoid', 101),
('/vandal/chronovoid/chronovoid_vandal_black/base.png', 'Vandal de la collection Chronovoid', 102),
('/vandal/chronovoid/chronovoid_vandal_purple/base.png', 'Vandal de la collection Chronovoid', 103),
('/vandal/chronovoid/chronovoid_vandal_red/base.png', 'Vandal de la collection Chronovoid', 104),
('/vandal/glitchpop/glitchpop_vandal_base/base.png', 'Vandal de la collection Glitchpop', 105),
('/vandal/glitchpop/glitchpop_vandal_blue/base.png', 'Vandal de la collection Glitchpop', 106),
('/vandal/glitchpop/glitchpop_vandal_gold/base.png', 'Vandal de la collection Glitchpop', 107),
('/vandal/glitchpop/glitchpop_vandal_red/base.png', 'Vandal de la collection Glitchpop', 108),
('/vandal/prime/prime_vandal_base/base.png', 'Vandal de la collection Prime', 109),
('/vandal/prime/prime_vandal_blue/base.png', 'Vandal de la collection Prime', 110),
('/vandal/prime/prime_vandal_gold/base.png', 'Vandal de la collection Prime', 111),
('/vandal/prime/prime_vandal_red/base.png', 'Vandal de la collection Prime', 112),
('/vandal/rgx/rgx_vandal_base/base.png', 'Vandal de la collection RGX11Z', 113),
('/vandal/rgx/rgx_vandal_blue/base.png', 'Vandal de la collection RGX11Z', 114),
('/vandal/rgx/rgx_vandal_red/base.png', 'Vandal de la collection RGX11Z', 115),
('/vandal/rgx/rgx_vandal_yellow/base.png', 'Vandal de la collection RGX11Z', 116),
('/vandal/reaver/reaver_vandal_base/base.png', 'Vandal de la collection Reaver', 117),
('/vandal/reaver/reaver_vandal_black/base.png', 'Vandal de la collection Reaver', 118),
('/vandal/reaver/reaver_vandal_red/base.png', 'Vandal de la collection Reaver', 119),
('/vandal/reaver/reaver_vandal_white/base.png', 'Vandal de la collection Reaver', 120),
('/phantom/champions/champions_phantom_base/base.png', 'Phantom de la collection Champions', 121),
('/phantom/glitchpop/glitchpop_phantom_base/base.png', 'Phantom de la collection Glitchpop', 122),
('/phantom/glitchpop/glitchpop_phantom_blue/base.png', 'Phantom de la collection Glitchpop', 123),
('/phantom/glitchpop/glitchpop_phantom_gold/base.png', 'Phantom de la collection Glitchpop', 124),
('/phantom/glitchpop/glitchpop_phantom_red/base.png', 'Phantom de la collection Glitchpop', 125),
('/phantom/oni/oni_phantom_base/base.png', 'Phantom de la collection Oni', 126),
('/phantom/oni/oni_phantom_black/base.png', 'Phantom de la collection Oni', 127),
('/phantom/oni/oni_phantom_green/base.png', 'Phantom de la collection Oni', 128),
('/phantom/oni/oni_phantom_white/base.png', 'Phantom de la collection Oni', 129),
('/phantom/ruination/ruination_phantom_base/base.png', 'Phantom de la collection Ruination', 130),
('/phantom/ruination/ruination_phantom_blue/base.png', 'Phantom de la collection Ruination', 131),
('/phantom/ruination/ruination_phantom_red/base.png', 'Phantom de la collection Ruination', 132),
('/phantom/ruination/ruination_phantom_yellow/base.png', 'Phantom de la collection Ruination', 133),
('/phantom/spectrum/spectrum_phantom_base/base.png', 'Phantom de la collection Spectrum', 134),
('/phantom/spectrum/spectrum_phantom_black/base.png', 'Phantom de la collection Spectrum', 135),
('/phantom/spectrum/spectrum_phantom_purple/base.png', 'Phantom de la collection Spectrum', 136),
('/phantom/spectrum/spectrum_phantom_red/base.png', 'Phantom de la collection Spectrum', 137),
('/phantom/valorantgov/valorantgov_phantom_base/base.png', 'Phantom de la collection Valorant Go', 138),
('/phantom/valorantgov/valorantgov_phantom_black/base.png', 'Phantom de la collection Valorant Go', 139),
('/phantom/valorantgov/valorantgov_phantom_purple/base.png', 'Phantom de la collection Valorant Go', 140),
('/phantom/valorantgov/valorantgov_phantom_red/base.png', 'Phantom de la collection Valorant Go', 141),
('/phantom/smorgasbord/smorgasbord_phantom_base/base.png', 'Phantom de la collection Smorgasbord', 142),
('/phantom/smorgasbord/smorgasbord_phantom_green/base.png', 'Phantom de la collection Smorgasbord', 143),
('/phantom/smorgasbord/smorgasbord_phantom_purple/base.png', 'Phantom de la collection Smorgasbord', 144),
('/phantom/smorgasbord/smorgasbord_phantom_red/base.png', 'Phantom de la collection Smorgasbord', 145),
('/phantom/smorgasbord/smorgasbord_phantom_yellow/base.png', 'Phantom de la collection Smorgasbord', 146),
('/operator/ion/ion_operator_base/base.png', 'Operator de la collection Ion', 147),
('/operator/ion/ion_operator_blue/base.png', 'Operator de la collection Ion', 148),
('/operator/ion/ion_operator_green/base.png', 'Operator de la collection Ion', 149),
('/operator/ion/ion_operator_yellow/base.png', 'Operator de la collection Ion', 150),
('/operator/rgx/rgx_operator_base/base.png', 'Operator de la collection RGX11Z', 151),
('/operator/rgx/rgx_operator_blue/base.png', 'Operator de la collection RGX11Z', 152),
('/operator/rgx/rgx_operator_red/base.png', 'Operator de la collection RGX11Z', 153),
('/operator/rgx/rgx_operator_yellow/base.png', 'Operator de la collection RGX11Z', 154),
('/operator/elderflame/elderflame_operator_base/base.png', 'Operator de la collection Elderflame', 155),
('/operator/elderflame/elderflame_operator_blue/base.png', 'Operator de la collection Elderflame', 156),
('/operator/elderflame/elderflame_operator_purple/base.png', 'Operator de la collection Elderflame', 157),
('/operator/elderflame/elderflame_operator_red/base.png', 'Operator de la collection Elderflame', 158),
('/operator/reaver/reaver_operator_base/base.png', 'Operator de la collection Reaver', 159),
('/operator/reaver/reaver_operator_black/base.png', 'Operator de la collection Reaver', 160),
('/operator/reaver/reaver_operator_red/base.png', 'Operator de la collection Reaver', 161),
('/operator/reaver/reaver_operator_white/base.png', 'Operator de la collection Reaver', 162),
('/operator/ruination/ruination_operator_base/base.png', 'Operator de la collection Ruination', 163),
('/operator/ruination/ruination_operator_black/base.png', 'Operator de la collection Ruination', 164),
('/operator/ruination/ruination_operator_purple/base.png', 'Operator de la collection Ruination', 165),
('/operator/ruination/ruination_operator_white/base.png', 'Operator de la collection Ruination', 166),
('/operator/spectrum/spectrum_operator_base/base.png', 'Operator de la collection Spectrum', 167),
('/operator/spectrum/spectrum_operator_black/base.png', 'Operator de la collection Spectrum', 168),
('/operator/spectrum/spectrum_operator_purple/base.png', 'Operator de la collection Spectrum', 169),
('/operator/spectrum/spectrum_operator_red/base.png', 'Operator de la collection Spectrum', 170),
('/operator/lycan/lycan_operator_base/base.png', 'Operator de la collection Lycan s Bane', 171),
('/operator/lycan/lycan_operator_red/base.png', 'Operator de la collection Lycan s Bane', 172),
('/operator/lycan/lycan_operator_green/base.png', 'Operator de la collection Lycan s Bane', 173),
('/operator/lycan/lycan_operator_purple/base.png', 'Operator de la collection Lycan s Bane', 174),


('/knife/kuronami/kuronami_knife_base/idle.png', 'couteau de la collection Kuronami - base', 1),
('/knife/kuronami/kuronami_knife_black/idle.png', 'couteau de la collection Kuronami - black', 2),
('/knife/kuronami/kuronami_knife_purple/idle.png', 'couteau de la collection Kuronami - purple', 3),
('/knife/kuronami/kuronami_knife_white/idle.png', 'couteau de la collection Kuronami - white', 4),
('/knife/ion/ion_knife_base/idle.png', 'Gantelet de la collection Ion - base', 5),
('/knife/ion/ion_knife_blue/idle.png', 'Gantelet de la collection Ion - blue', 6),
('/knife/ion/ion_knife_green/idle.png', 'Gantelet de la collection Ion - green', 7),
('/knife/ion/ion_knife_orange/idle.png', 'Gantelet de la collection Ion - orange', 8),
('/knife/oni/oni_knife_base/idle.png', 'Katana de la collection Oni - base', 9),
('/knife/oni/oni_knife_black/idle.png', 'Katana de la collection Oni - black', 10),
('/knife/oni/oni_knife_green/idle.png', 'Katana de la collection Oni - green', 11),
('/knife/oni/oni_knife_white/idle.png', 'Katana de la collection Oni - white', 12),
('/classic/glitchpop/glitchpop_classic_base/idle.png', 'Classic de la collection Glitchpop - base', 13),
('/classic/glitchpop/glitchpop_classic_blue/idle.png', 'Classic de la collection Glitchpop - blue', 14),
('/classic/glitchpop/glitchpop_classic_gold/idle.png', 'Classic de la collection Glitchpop - gold', 15),
('/classic/glitchpop/glitchpop_classic_red/idle.png', 'Classic de la collection Glitchpop - red', 16),
('/classic/prime/prime_classic_base/idle.png', 'Classic de la collection Prime - base', 17),
('/classic/prime/prime_classic_blue/idle.png', 'Classic de la collection Prime - blue', 18),
('/classic/prime/prime_classic_gold/idle.png', 'Classic de la collection Prime - gold', 19),
('/classic/prime/prime_classic_red/idle.png', 'Classic de la collection Prime - red', 20),
('/classic/spectrum/spectrum_classic_base/idle.png', 'Classic de la collection Spectrum - base', 21),
('/classic/spectrum/spectrum_classic_black/idle.png', 'Classic de la collection Spectrum - black', 22),
('/classic/spectrum/spectrum_classic_purple/idle.png', 'Classic de la collection Spectrum - purple', 23),
('/classic/spectrum/spectrum_classic_red/idle.png', 'Classic de la collection Spectrum - red', 24),
('/shorty/oni/oni_shorty_base/idle.png', 'Shorty de la collection Oni - base', 25),
('/shorty/oni/oni_shorty_black/idle.png', 'Shorty de la collection Oni - black', 26),
('/shorty/oni/oni_shorty_green/idle.png', 'Shorty de la collection Oni - green', 27),
('/shorty/oni/oni_shorty_white/idle.png', 'Shorty de la collection Oni - white', 28),
('/shorty/sotl/sotl_shorty_base/idle.png', 'Shorty de la collection Sentinels of the light - base', 29),
('/shorty/sotl/sotl_shorty_purple/idle.png', 'Shorty de la collection Sentinels of the light - purple', 30),
('/shorty/sotl/sotl_shorty_pink/idle.png', 'Shorty de la collection Sentinels of the light - pink', 31),
('/shorty/sotl/sotl_shorty_green/idle.png', 'Shorty de la collection Sentinels of the light - green', 32),
('/shorty/ptc/ptc_shorty_base/idle.png', 'Shorty de la collection Prelude to Chaos - base', 33),
('/shorty/ptc/ptc_shorty_blue/idle.png', 'Shorty de la collection Prelude to Chaos - blue', 34),
('/shorty/ptc/ptc_shorty_green/idle.png', 'Shorty de la collection Prelude to Chaos - green', 35),
('/shorty/ptc/ptc_shorty_white/idle.png', 'Shorty de la collection Prelude to Chaos - white', 36),
('/frenzy/prime/prime_frenzy_base/idle.png', 'Frenzy de la collection Prime//2.0 - base', 37),
('/frenzy/prime/prime_frenzy_blue/idle.png', 'Frenzy de la collection Prime//2.0 - blue', 38),
('/frenzy/prime/prime_frenzy_gold/idle.png', 'Frenzy de la collection Prime//2.0 - gold', 39),
('/frenzy/prime/prime_frenzy_red/idle.png', 'Frenzy de la collection Prime//2.0 - red', 40),
('/frenzy/glitchpop/glitchpop_frenzy_base/idle.png', 'Frenzy de la collection Glitchpop - base', 41),
('/frenzy/glitchpop/glitchpop_frenzy_blue/idle.png', 'Frenzy de la collection Glitchpop - blue', 42),
('/frenzy/glitchpop/glitchpop_frenzy_gold/idle.png', 'Frenzy de la collection Glitchpop - gold', 43),
('/frenzy/glitchpop/glitchpop_frenzy_red/idle.png', 'Frenzy de la collection Glitchpop - red', 44),
('/frenzy/ion/ion_frenzy_base/idle.png', 'Frenzy de la collection Ion - base', 45),
('/frenzy/ion/ion_frenzy_blue/idle.png', 'Frenzy de la collection Ion - blue', 46),
('/frenzy/ion/ion_frenzy_green/idle.png', 'Frenzy de la collection Ion - green', 47),
('/frenzy/ion/ion_frenzy_orange/idle.png', 'Frenzy de la collection Ion - orange', 48),
('/ghost/gaia/gaia_ghost_base/idle.png', 'Ghost de la collection Gaia s vengeance - base', 49),
('/ghost/gaia/gaia_ghost_blue/idle.png', 'Ghost de la collection Gaia s vengeance - blue', 50),
('/ghost/gaia/gaia_ghost_green/idle.png', 'Ghost de la collection Gaia s vengeance - green', 51),
('/ghost/gaia/gaia_ghost_red/idle.png', 'Ghost de la collection Gaia s vengeance - red', 52),
('/ghost/reaver/reaver_ghost_base/idle.png', 'Ghost de la collection Reaver - base', 53),
('/ghost/reaver/reaver_ghost_black/idle.png', 'Ghost de la collection Reaver - black', 54),
('/ghost/reaver/reaver_ghost_red/idle.png', 'Ghost de la collection Reaver - red', 55),
('/ghost/reaver/reaver_ghost_white/idle.png', 'Ghost de la collection Reaver - white', 56),
('/ghost/res/res_ghost_base/idle.png', 'Ghost de la collection Radiant Entertainment System', 57),
('/ghost/res/res_ghost_purple/idle.png', 'Ghost de la collection Radiant Entertainment System', 58),
('/ghost/res/res_ghost_red/idle.png', 'Ghost de la collection Radiant Entertainment System', 59),
('/sheriff/arcane/arcane_sheriff_base/idle.png', 'Sheriff de l edition limitee Arcane', 60),
('/sheriff/reaver/reaver_sheriff_base/idle.png', 'Sheriff de la collection Reaver', 61),
('/sheriff/reaver/reaver_sheriff_black/idle.png', 'Sheriff de la collection Reaver', 62),
('/sheriff/reaver/reaver_sheriff_red/idle.png', 'Sheriff de la collection Reaver', 63),
('/sheriff/reaver/reaver_sheriff_white/idle.png', 'Sheriff de la collection Reaver', 64),
('/sheriff/sotl/sotl_sheriff_base/idle.png', 'Sheriff de la collection Sentinel of the Light', 65),
('/sheriff/sotl/sotl_sheriff_green/idle.png', 'Sheriff de la collection Sentinel of the Light', 66),
('/sheriff/sotl/sotl_sheriff_pink/idle.png', 'Sheriff de la collection Sentinel of the Light', 67),
('/sheriff/sotl/sotl_sheriff_purple/idle.png', 'Sheriff de la collection Sentinel of the Light', 68),
('/stinger/ptc/ptc_stinger_base/idle.png', 'Stinger de la collection Prelude to Chaos', 69),
('/stinger/ptc/ptc_stinger_blue/idle.png', 'Stinger de la collection Prelude to Chaos', 70),
('/stinger/ptc/ptc_stinger_green/idle.png', 'Stinger de la collection Prelude to Chaos', 71),
('/stinger/ptc/ptc_stinger_white/idle.png', 'Stinger de la collection Prelude to Chaos', 72),
('/stinger/rgx/rgx_stinger_base/idle.png', 'Stinger de la collection RGX11Z', 73),
('/stinger/rgx/rgx_stinger_blue/idle.png', 'Stinger de la collection RGX11Z', 74),
('/stinger/rgx/rgx_stinger_red/idle.png', 'Stinger de la collection RGX11Z', 75),
('/stinger/rgx/rgx_stinger_yellow/idle.png', 'Stinger de la collection RGX11Z', 76),
('/stinger/regen/regen_stinger_base/idle.png', 'Stinger de la collection Reaver', 77),
('/stinger/regen/regen_stinger_black/idle.png', 'Stinger de la collection Reaver', 78),
('/stinger/regen/regen_stinger_red/idle.png', 'Stinger de la collection Reaver', 79),
('/stinger/regen/regen_stinger_white/idle.png', 'Stinger de la collection Reaver', 80),
('/stinger/spectrum/spectrum_stinger_base/idle.png', 'Stinger de la collection Spectrum', 81),
('/stinger/spectrum/spectrum_stinger_black/idle.png', 'Stinger de la collection Spectrum', 82),
('/stinger/spectrum/spectrum_stinger_purple/idle.png', 'Stinger de la collection Spectrum', 83),
('/stinger/spectrum/spectrum_stinger_red/idle.png', 'Stinger de la collection Spectrum', 84),
('/bulldog/glitchpop/glitchpop_bulldog_base/idle.png', 'Bulldog de la collection Glitchpop', 85),
('/bulldog/glitchpop/glitchpop_bulldog_blue/idle.png', 'Bulldog de la collection Glitchpop', 86),
('/bulldog/glitchpop/glitchpop_bulldog_gold/idle.png', 'Bulldog de la collection Glitchpop', 87),
('/bulldog/glitchpop/glitchpop_bulldog_red/idle.png', 'Bulldog de la collection Glitchpop', 88),
('/bulldog/magepunk/magepunk_bulldog_base/idle.png', 'Bulldog de la collection Magepunk', 89),
('/bulldog/magepunk/magepunk_bulldog_green/idle.png', 'Bulldog de la collection Magepunk', 90),
('/bulldog/magepunk/magepunk_bulldog_orange/idle.png', 'Bulldog de la collection Magepunk', 91),
('/bulldog/magepunk/magepunk_bulldog_purple/idle.png', 'Bulldog de la collection Magepunk', 92),
('/guardian/gaia/gaia_guardian_base/idle.png', 'Guardian de la collection Gaia s vengeance', 93),
('/guardian/gaia/gaia_guardian_blue/idle.png', 'Guardian de la collection Gaia s vengeance', 94),
('/guardian/gaia/gaia_guardian_green/idle.png', 'Guardian de la collection Gaia s vengeance', 95),
('/guardian/gaia/gaia_guardian_red/idle.png', 'Guardian de la collection Gaia s vengeance', 96),
('/guardian/protocol/protocol_guardian_base/idle.png', 'Guardian de la collection Protocol', 97),
('/guardian/protocol/protocol_guardian_blue/idle.png', 'Guardian de la collection Protocol', 98),
('/guardian/protocol/protocol_guardian_orange/idle.png', 'Guardian de la collection Protocol', 99),
('/guardian/protocol/protocol_guardian_red/idle.png', 'Guardian de la collection Protocol', 100),
('/vandal/chronovoid/chronovoid_vandal_base/idle.png', 'Vandal de la collection Chronovoid', 101),
('/vandal/chronovoid/chronovoid_vandal_black/idle.png', 'Vandal de la collection Chronovoid', 102),
('/vandal/chronovoid/chronovoid_vandal_purple/idle.png', 'Vandal de la collection Chronovoid', 103),
('/vandal/chronovoid/chronovoid_vandal_red/idle.png', 'Vandal de la collection Chronovoid', 104),
('/vandal/glitchpop/glitchpop_vandal_base/idle.png', 'Vandal de la collection Glitchpop', 105),
('/vandal/glitchpop/glitchpop_vandal_blue/idle.png', 'Vandal de la collection Glitchpop', 106),
('/vandal/glitchpop/glitchpop_vandal_gold/idle.png', 'Vandal de la collection Glitchpop', 107),
('/vandal/glitchpop/glitchpop_vandal_red/idle.png', 'Vandal de la collection Glitchpop', 108),
('/vandal/prime/prime_vandal_base/idle.png', 'Vandal de la collection Prime', 109),
('/vandal/prime/prime_vandal_blue/idle.png', 'Vandal de la collection Prime', 110),
('/vandal/prime/prime_vandal_gold/idle.png', 'Vandal de la collection Prime', 111),
('/vandal/prime/prime_vandal_red/idle.png', 'Vandal de la collection Prime', 112),
('/vandal/rgx/rgx_vandal_base/idle.png', 'Vandal de la collection RGX11Z', 113),
('/vandal/rgx/rgx_vandal_blue/idle.png', 'Vandal de la collection RGX11Z', 114),
('/vandal/rgx/rgx_vandal_red/idle.png', 'Vandal de la collection RGX11Z', 115),
('/vandal/rgx/rgx_vandal_yellow/idle.png', 'Vandal de la collection RGX11Z', 116),
('/vandal/reaver/reaver_vandal_base/idle.png', 'Vandal de la collection Reaver', 117),
('/vandal/reaver/reaver_vandal_black/idle.png', 'Vandal de la collection Reaver', 118),
('/vandal/reaver/reaver_vandal_red/idle.png', 'Vandal de la collection Reaver', 119),
('/vandal/reaver/reaver_vandal_white/idle.png', 'Vandal de la collection Reaver', 120),
('/phantom/champions/champions_phantom_base/idle.png', 'Phantom de la collection Champions', 121),
('/phantom/glitchpop/glitchpop_phantom_base/idle.png', 'Phantom de la collection Glitchpop', 122),
('/phantom/glitchpop/glitchpop_phantom_blue/idle.png', 'Phantom de la collection Glitchpop', 123),
('/phantom/glitchpop/glitchpop_phantom_gold/idle.png', 'Phantom de la collection Glitchpop', 124),
('/phantom/glitchpop/glitchpop_phantom_red/idle.png', 'Phantom de la collection Glitchpop', 125),
('/phantom/oni/oni_phantom_base/idle.png', 'Phantom de la collection Oni', 126),
('/phantom/oni/oni_phantom_black/idle.png', 'Phantom de la collection Oni', 127),
('/phantom/oni/oni_phantom_green/idle.png', 'Phantom de la collection Oni', 128),
('/phantom/oni/oni_phantom_white/idle.png', 'Phantom de la collection Oni', 129),
('/phantom/ruination/ruination_phantom_base/idle.png', 'Phantom de la collection Ruination', 130),
('/phantom/ruination/ruination_phantom_blue/idle.png', 'Phantom de la collection Ruination', 131),
('/phantom/ruination/ruination_phantom_red/idle.png', 'Phantom de la collection Ruination', 132),
('/phantom/ruination/ruination_phantom_yellow/idle.png', 'Phantom de la collection Ruination', 133),
('/phantom/spectrum/spectrum_phantom_base/idle.png', 'Phantom de la collection Spectrum', 134),
('/phantom/spectrum/spectrum_phantom_black/idle.png', 'Phantom de la collection Spectrum', 135),
('/phantom/spectrum/spectrum_phantom_purple/idle.png', 'Phantom de la collection Spectrum', 136),
('/phantom/spectrum/spectrum_phantom_red/idle.png', 'Phantom de la collection Spectrum', 137),
('/phantom/valorantgov/valorantgov_phantom_base/idle.png', 'Phantom de la collection Valorant Go', 138),
('/phantom/valorantgov/valorantgov_phantom_black/idle.png', 'Phantom de la collection Valorant Go', 139),
('/phantom/valorantgov/valorantgov_phantom_purple/idle.png', 'Phantom de la collection Valorant Go', 140),
('/phantom/valorantgov/valorantgov_phantom_red/idle.png', 'Phantom de la collection Valorant Go', 141),
('/phantom/smorgasbord/smorgasbord_phantom_base/idle.png', 'Phantom de la collection Smorgasbord', 142),
('/phantom/smorgasbord/smorgasbord_phantom_green/idle.png', 'Phantom de la collection Smorgasbord', 143),
('/phantom/smorgasbord/smorgasbord_phantom_purple/idle.png', 'Phantom de la collection Smorgasbord', 144),
('/phantom/smorgasbord/smorgasbord_phantom_red/idle.png', 'Phantom de la collection Smorgasbord', 145),
('/phantom/smorgasbord/smorgasbord_phantom_yellow/idle.png', 'Phantom de la collection Smorgasbord', 146),
('/operator/ion/ion_operator_base/idle.png', 'Operator de la collection Ion', 147),
('/operator/ion/ion_operator_blue/idle.png', 'Operator de la collection Ion', 148),
('/operator/ion/ion_operator_green/idle.png', 'Operator de la collection Ion', 149),
('/operator/ion/ion_operator_yellow/idle.png', 'Operator de la collection Ion', 150),
('/operator/rgx/rgx_operator_base/idle.png', 'Operator de la collection RGX11Z', 151),
('/operator/rgx/rgx_operator_blue/idle.png', 'Operator de la collection RGX11Z', 152),
('/operator/rgx/rgx_operator_red/idle.png', 'Operator de la collection RGX11Z', 153),
('/operator/rgx/rgx_operator_yellow/idle.png', 'Operator de la collection RGX11Z', 154),
('/operator/elderflame/elderflame_operator_base/idle.png', 'Operator de la collection Elderflame', 155),
('/operator/elderflame/elderflame_operator_blue/idle.png', 'Operator de la collection Elderflame', 156),
('/operator/elderflame/elderflame_operator_purple/idle.png', 'Operator de la collection Elderflame', 157),
('/operator/elderflame/elderflame_operator_red/idle.png', 'Operator de la collection Elderflame', 158),
('/operator/reaver/reaver_operator_base/idle.png', 'Operator de la collection Reaver', 159),
('/operator/reaver/reaver_operator_black/idle.png', 'Operator de la collection Reaver', 160),
('/operator/reaver/reaver_operator_red/idle.png', 'Operator de la collection Reaver', 161),
('/operator/reaver/reaver_operator_white/idle.png', 'Operator de la collection Reaver', 162),
('/operator/ruination/ruination_operator_base/idle.png', 'Operator de la collection Ruination', 163),
('/operator/ruination/ruination_operator_black/idle.png', 'Operator de la collection Ruination', 164),
('/operator/ruination/ruination_operator_purple/idle.png', 'Operator de la collection Ruination', 165),
('/operator/ruination/ruination_operator_white/idle.png', 'Operator de la collection Ruination', 166),
('/operator/spectrum/spectrum_operator_base/idle.png', 'Operator de la collection Spectrum', 167),
('/operator/spectrum/spectrum_operator_black/idle.png', 'Operator de la collection Spectrum', 168),
('/operator/spectrum/spectrum_operator_purple/idle.png', 'Operator de la collection Spectrum', 169),
('/operator/spectrum/spectrum_operator_red/idle.png', 'Operator de la collection Spectrum', 170),
('/operator/lycan/lycan_operator_base/idle.png', 'Operator de la collection Lycan s Bane', 171),
('/operator/lycan/lycan_operator_red/idle.png', 'Operator de la collection Lycan s Bane', 172),
('/operator/lycan/lycan_operator_green/idle.png', 'Operator de la collection Lycan s Bane', 173),
('/operator/lycan/lycan_operator_purple/idle.png', 'Operator de la collection Lycan s Bane', 174),


('/knife/kuronami/kuronami_knife_base/inspect.png', 'couteau de la collection Kuronami - base', 1),
('/knife/kuronami/kuronami_knife_black/inspect.png', 'couteau de la collection Kuronami - black', 2),
('/knife/kuronami/kuronami_knife_purple/inspect.png', 'couteau de la collection Kuronami - purple', 3),
('/knife/kuronami/kuronami_knife_white/inspect.png', 'couteau de la collection Kuronami - white', 4),
('/knife/ion/ion_knife_base/inspect.png', 'Gantelet de la collection Ion - base', 5),
('/knife/ion/ion_knife_blue/inspect.png', 'Gantelet de la collection Ion - blue', 6),
('/knife/ion/ion_knife_green/inspect.png', 'Gantelet de la collection Ion - green', 7),
('/knife/ion/ion_knife_orange/inspect.png', 'Gantelet de la collection Ion - orange', 8),
('/knife/oni/oni_knife_base/inspect.png', 'Katana de la collection Oni - base', 9),
('/knife/oni/oni_knife_black/inspect.png', 'Katana de la collection Oni - black', 10),
('/knife/oni/oni_knife_green/inspect.png', 'Katana de la collection Oni - green', 11),
('/knife/oni/oni_knife_white/inspect.png', 'Katana de la collection Oni - white', 12),
('/classic/glitchpop/glitchpop_classic_base/inspect.png', 'Classic de la collection Glitchpop - base', 13),
('/classic/glitchpop/glitchpop_classic_blue/inspect.png', 'Classic de la collection Glitchpop - blue', 14),
('/classic/glitchpop/glitchpop_classic_gold/inspect.png', 'Classic de la collection Glitchpop - gold', 15),
('/classic/glitchpop/glitchpop_classic_red/inspect.png', 'Classic de la collection Glitchpop - red', 16),
('/classic/prime/prime_classic_base/inspect.png', 'Classic de la collection Prime - base', 17),
('/classic/prime/prime_classic_blue/inspect.png', 'Classic de la collection Prime - blue', 18),
('/classic/prime/prime_classic_gold/inspect.png', 'Classic de la collection Prime - gold', 19),
('/classic/prime/prime_classic_red/inspect.png', 'Classic de la collection Prime - red', 20),
('/classic/spectrum/spectrum_classic_base/inspect.png', 'Classic de la collection Spectrum - base', 21),
('/classic/spectrum/spectrum_classic_black/inspect.png', 'Classic de la collection Spectrum - black', 22),
('/classic/spectrum/spectrum_classic_purple/inspect.png', 'Classic de la collection Spectrum - purple', 23),
('/classic/spectrum/spectrum_classic_red/inspect.png', 'Classic de la collection Spectrum - red', 24),
('/shorty/oni/oni_shorty_base/inspect.png', 'Shorty de la collection Oni - base', 25),
('/shorty/oni/oni_shorty_black/inspect.png', 'Shorty de la collection Oni - black', 26),
('/shorty/oni/oni_shorty_green/inspect.png', 'Shorty de la collection Oni - green', 27),
('/shorty/oni/oni_shorty_white/inspect.png', 'Shorty de la collection Oni - white', 28),
('/shorty/sotl/sotl_shorty_base/inspect.png', 'Shorty de la collection Sentinels of the light - base', 29),
('/shorty/sotl/sotl_shorty_purple/inspect.png', 'Shorty de la collection Sentinels of the light - purple', 30),
('/shorty/sotl/sotl_shorty_pink/inspect.png', 'Shorty de la collection Sentinels of the light - pink', 31),
('/shorty/sotl/sotl_shorty_green/inspect.png', 'Shorty de la collection Sentinels of the light - green', 32),
('/shorty/ptc/ptc_shorty_base/inspect.png', 'Shorty de la collection Prelude to Chaos - base', 33),
('/shorty/ptc/ptc_shorty_blue/inspect.png', 'Shorty de la collection Prelude to Chaos - blue', 34),
('/shorty/ptc/ptc_shorty_green/inspect.png', 'Shorty de la collection Prelude to Chaos - green', 35),
('/shorty/ptc/ptc_shorty_white/inspect.png', 'Shorty de la collection Prelude to Chaos - white', 36),
('/frenzy/prime/prime_frenzy_base/inspect.png', 'Frenzy de la collection Prime//2.0 - base', 37),
('/frenzy/prime/prime_frenzy_blue/inspect.png', 'Frenzy de la collection Prime//2.0 - blue', 38),
('/frenzy/prime/prime_frenzy_gold/inspect.png', 'Frenzy de la collection Prime//2.0 - gold', 39),
('/frenzy/prime/prime_frenzy_red/inspect.png', 'Frenzy de la collection Prime//2.0 - red', 40),
('/frenzy/glitchpop/glitchpop_frenzy_base/inspect.png', 'Frenzy de la collection Glitchpop - base', 41),
('/frenzy/glitchpop/glitchpop_frenzy_blue/inspect.png', 'Frenzy de la collection Glitchpop - blue', 42),
('/frenzy/glitchpop/glitchpop_frenzy_gold/inspect.png', 'Frenzy de la collection Glitchpop - gold', 43),
('/frenzy/glitchpop/glitchpop_frenzy_red/inspect.png', 'Frenzy de la collection Glitchpop - red', 44),
('/frenzy/ion/ion_frenzy_base/inspect.png', 'Frenzy de la collection Ion - base', 45),
('/frenzy/ion/ion_frenzy_blue/inspect.png', 'Frenzy de la collection Ion - blue', 46),
('/frenzy/ion/ion_frenzy_green/inspect.png', 'Frenzy de la collection Ion - green', 47),
('/frenzy/ion/ion_frenzy_orange/inspect.png', 'Frenzy de la collection Ion - orange', 48),
('/ghost/gaia/gaia_ghost_base/inspect.png', 'Ghost de la collection Gaia s vengeance - base', 49),
('/ghost/gaia/gaia_ghost_blue/inspect.png', 'Ghost de la collection Gaia s vengeance - blue', 50),
('/ghost/gaia/gaia_ghost_green/inspect.png', 'Ghost de la collection Gaia s vengeance - green', 51),
('/ghost/gaia/gaia_ghost_red/inspect.png', 'Ghost de la collection Gaia s vengeance - red', 52),
('/ghost/reaver/reaver_ghost_base/inspect.png', 'Ghost de la collection Reaver - base', 53),
('/ghost/reaver/reaver_ghost_black/inspect.png', 'Ghost de la collection Reaver - black', 54),
('/ghost/reaver/reaver_ghost_red/inspect.png', 'Ghost de la collection Reaver - red', 55),
('/ghost/reaver/reaver_ghost_white/inspect.png', 'Ghost de la collection Reaver - white', 56),
('/ghost/res/res_ghost_base/inspect.png', 'Ghost de la collection Radiant Entertainment System', 57),
('/ghost/res/res_ghost_purple/inspect.png', 'Ghost de la collection Radiant Entertainment System', 58),
('/ghost/res/res_ghost_red/inspect.png', 'Ghost de la collection Radiant Entertainment System', 59),
('/sheriff/arcane/arcane_sheriff_base/inspect.png', 'Sheriff de l edition limitee Arcane', 60),
('/sheriff/reaver/reaver_sheriff_base/inspect.png', 'Sheriff de la collection Reaver', 61),
('/sheriff/reaver/reaver_sheriff_black/inspect.png', 'Sheriff de la collection Reaver', 62),
('/sheriff/reaver/reaver_sheriff_red/inspect.png', 'Sheriff de la collection Reaver', 63),
('/sheriff/reaver/reaver_sheriff_white/inspect.png', 'Sheriff de la collection Reaver', 64),
('/sheriff/sotl/sotl_sheriff_base/inspect.png', 'Sheriff de la collection Sentinel of the Light', 65),
('/sheriff/sotl/sotl_sheriff_green/inspect.png', 'Sheriff de la collection Sentinel of the Light', 66),
('/sheriff/sotl/sotl_sheriff_pink/inspect.png', 'Sheriff de la collection Sentinel of the Light', 67),
('/sheriff/sotl/sotl_sheriff_purple/inspect.png', 'Sheriff de la collection Sentinel of the Light', 68),
('/stinger/ptc/ptc_stinger_base/inspect.png', 'Stinger de la collection Prelude to Chaos', 69),
('/stinger/ptc/ptc_stinger_blue/inspect.png', 'Stinger de la collection Prelude to Chaos', 70),
('/stinger/ptc/ptc_stinger_green/inspect.png', 'Stinger de la collection Prelude to Chaos', 71),
('/stinger/ptc/ptc_stinger_white/inspect.png', 'Stinger de la collection Prelude to Chaos', 72),
('/stinger/rgx/rgx_stinger_base/inspect.png', 'Stinger de la collection RGX11Z', 73),
('/stinger/rgx/rgx_stinger_blue/inspect.png', 'Stinger de la collection RGX11Z', 74),
('/stinger/rgx/rgx_stinger_red/inspect.png', 'Stinger de la collection RGX11Z', 75),
('/stinger/rgx/rgx_stinger_yellow/inspect.png', 'Stinger de la collection RGX11Z', 76),
('/stinger/regen/regen_stinger_base/inspect.png', 'Stinger de la collection Reaver', 77),
('/stinger/regen/regen_stinger_black/inspect.png', 'Stinger de la collection Reaver', 78),
('/stinger/regen/regen_stinger_red/inspect.png', 'Stinger de la collection Reaver', 79),
('/stinger/regen/regen_stinger_white/inspect.png', 'Stinger de la collection Reaver', 80),
('/stinger/spectrum/spectrum_stinger_base/inspect.png', 'Stinger de la collection Spectrum', 81),
('/stinger/spectrum/spectrum_stinger_black/inspect.png', 'Stinger de la collection Spectrum', 82),
('/stinger/spectrum/spectrum_stinger_purple/inspect.png', 'Stinger de la collection Spectrum', 83),
('/stinger/spectrum/spectrum_stinger_red/inspect.png', 'Stinger de la collection Spectrum', 84),
('/bulldog/glitchpop/glitchpop_bulldog_base/inspect.png', 'Bulldog de la collection Glitchpop', 85),
('/bulldog/glitchpop/glitchpop_bulldog_blue/inspect.png', 'Bulldog de la collection Glitchpop', 86),
('/bulldog/glitchpop/glitchpop_bulldog_gold/inspect.png', 'Bulldog de la collection Glitchpop', 87),
('/bulldog/glitchpop/glitchpop_bulldog_red/inspect.png', 'Bulldog de la collection Glitchpop', 88),
('/bulldog/magepunk/magepunk_bulldog_base/inspect.png', 'Bulldog de la collection Magepunk', 89),
('/bulldog/magepunk/magepunk_bulldog_green/inspect.png', 'Bulldog de la collection Magepunk', 90),
('/bulldog/magepunk/magepunk_bulldog_orange/inspect.png', 'Bulldog de la collection Magepunk', 91),
('/bulldog/magepunk/magepunk_bulldog_purple/inspect.png', 'Bulldog de la collection Magepunk', 92),
('/guardian/gaia/gaia_guardian_base/inspect.png', 'Guardian de la collection Gaia s vengeance', 93),
('/guardian/gaia/gaia_guardian_blue/inspect.png', 'Guardian de la collection Gaia s vengeance', 94),
('/guardian/gaia/gaia_guardian_green/inspect.png', 'Guardian de la collection Gaia s vengeance', 95),
('/guardian/gaia/gaia_guardian_red/inspect.png', 'Guardian de la collection Gaia s vengeance', 96),
('/guardian/protocol/protocol_guardian_base/inspect.png', 'Guardian de la collection Protocol', 97),
('/guardian/protocol/protocol_guardian_blue/inspect.png', 'Guardian de la collection Protocol', 98),
('/guardian/protocol/protocol_guardian_orange/inspect.png', 'Guardian de la collection Protocol', 99),
('/guardian/protocol/protocol_guardian_red/inspect.png', 'Guardian de la collection Protocol', 100),
('/vandal/chronovoid/chronovoid_vandal_base/inspect.png', 'Vandal de la collection Chronovoid', 101),
('/vandal/chronovoid/chronovoid_vandal_black/inspect.png', 'Vandal de la collection Chronovoid', 102),
('/vandal/chronovoid/chronovoid_vandal_purple/inspect.png', 'Vandal de la collection Chronovoid', 103),
('/vandal/chronovoid/chronovoid_vandal_red/inspect.png', 'Vandal de la collection Chronovoid', 104),
('/vandal/glitchpop/glitchpop_vandal_base/inspect.png', 'Vandal de la collection Glitchpop', 105),
('/vandal/glitchpop/glitchpop_vandal_blue/inspect.png', 'Vandal de la collection Glitchpop', 106),
('/vandal/glitchpop/glitchpop_vandal_gold/inspect.png', 'Vandal de la collection Glitchpop', 107),
('/vandal/glitchpop/glitchpop_vandal_red/inspect.png', 'Vandal de la collection Glitchpop', 108),
('/vandal/prime/prime_vandal_base/inspect.png', 'Vandal de la collection Prime', 109),
('/vandal/prime/prime_vandal_blue/inspect.png', 'Vandal de la collection Prime', 110),
('/vandal/prime/prime_vandal_gold/inspect.png', 'Vandal de la collection Prime', 111),
('/vandal/prime/prime_vandal_red/inspect.png', 'Vandal de la collection Prime', 112),
('/vandal/rgx/rgx_vandal_base/inspect.png', 'Vandal de la collection RGX11Z', 113),
('/vandal/rgx/rgx_vandal_blue/inspect.png', 'Vandal de la collection RGX11Z', 114),
('/vandal/rgx/rgx_vandal_red/inspect.png', 'Vandal de la collection RGX11Z', 115),
('/vandal/rgx/rgx_vandal_yellow/inspect.png', 'Vandal de la collection RGX11Z', 116),
('/vandal/reaver/reaver_vandal_base/inspect.png', 'Vandal de la collection Reaver', 117),
('/vandal/reaver/reaver_vandal_black/inspect.png', 'Vandal de la collection Reaver', 118),
('/vandal/reaver/reaver_vandal_red/inspect.png', 'Vandal de la collection Reaver', 119),
('/vandal/reaver/reaver_vandal_white/inspect.png', 'Vandal de la collection Reaver', 120),
('/phantom/champions/champions_phantom_base/inspect.png', 'Phantom de la collection Champions', 121),
('/phantom/glitchpop/glitchpop_phantom_base/inspect.png', 'Phantom de la collection Glitchpop', 122),
('/phantom/glitchpop/glitchpop_phantom_blue/inspect.png', 'Phantom de la collection Glitchpop', 123),
('/phantom/glitchpop/glitchpop_phantom_gold/inspect.png', 'Phantom de la collection Glitchpop', 124),
('/phantom/glitchpop/glitchpop_phantom_red/inspect.png', 'Phantom de la collection Glitchpop', 125),
('/phantom/oni/oni_phantom_base/inspect.png', 'Phantom de la collection Oni', 126),
('/phantom/oni/oni_phantom_black/inspect.png', 'Phantom de la collection Oni', 127),
('/phantom/oni/oni_phantom_green/inspect.png', 'Phantom de la collection Oni', 128),
('/phantom/oni/oni_phantom_white/inspect.png', 'Phantom de la collection Oni', 129),
('/phantom/ruination/ruination_phantom_base/inspect.png', 'Phantom de la collection Ruination', 130),
('/phantom/ruination/ruination_phantom_blue/inspect.png', 'Phantom de la collection Ruination', 131),
('/phantom/ruination/ruination_phantom_red/inspect.png', 'Phantom de la collection Ruination', 132),
('/phantom/ruination/ruination_phantom_yellow/inspect.png', 'Phantom de la collection Ruination', 133),
('/phantom/spectrum/spectrum_phantom_base/inspect.png', 'Phantom de la collection Spectrum', 134),
('/phantom/spectrum/spectrum_phantom_black/inspect.png', 'Phantom de la collection Spectrum', 135),
('/phantom/spectrum/spectrum_phantom_purple/inspect.png', 'Phantom de la collection Spectrum', 136),
('/phantom/spectrum/spectrum_phantom_red/inspect.png', 'Phantom de la collection Spectrum', 137),
('/phantom/valorantgov/valorantgov_phantom_base/inspect.png', 'Phantom de la collection Valorant Go', 138),
('/phantom/valorantgov/valorantgov_phantom_black/inspect.png', 'Phantom de la collection Valorant Go', 139),
('/phantom/valorantgov/valorantgov_phantom_purple/inspect.png', 'Phantom de la collection Valorant Go', 140),
('/phantom/valorantgov/valorantgov_phantom_red/inspect.png', 'Phantom de la collection Valorant Go', 141),
('/phantom/smorgasbord/smorgasbord_phantom_base/inspect.png', 'Phantom de la collection Smorgasbord', 142),
('/phantom/smorgasbord/smorgasbord_phantom_green/inspect.png', 'Phantom de la collection Smorgasbord', 143),
('/phantom/smorgasbord/smorgasbord_phantom_purple/inspect.png', 'Phantom de la collection Smorgasbord', 144),
('/phantom/smorgasbord/smorgasbord_phantom_red/inspect.png', 'Phantom de la collection Smorgasbord', 145),
('/phantom/smorgasbord/smorgasbord_phantom_yellow/inspect.png', 'Phantom de la collection Smorgasbord', 146),
('/operator/ion/ion_operator_base/inspect.png', 'Operator de la collection Ion', 147),
('/operator/ion/ion_operator_blue/inspect.png', 'Operator de la collection Ion', 148),
('/operator/ion/ion_operator_green/inspect.png', 'Operator de la collection Ion', 149),
('/operator/ion/ion_operator_yellow/inspect.png', 'Operator de la collection Ion', 150),
('/operator/rgx/rgx_operator_base/inspect.png', 'Operator de la collection RGX11Z', 151),
('/operator/rgx/rgx_operator_blue/inspect.png', 'Operator de la collection RGX11Z', 152),
('/operator/rgx/rgx_operator_red/inspect.png', 'Operator de la collection RGX11Z', 153),
('/operator/rgx/rgx_operator_yellow/inspect.png', 'Operator de la collection RGX11Z', 154),
('/operator/elderflame/elderflame_operator_base/inspect.png', 'Operator de la collection Elderflame', 155),
('/operator/elderflame/elderflame_operator_blue/inspect.png', 'Operator de la collection Elderflame', 156),
('/operator/elderflame/elderflame_operator_purple/inspect.png', 'Operator de la collection Elderflame', 157),
('/operator/elderflame/elderflame_operator_red/inspect.png', 'Operator de la collection Elderflame', 158),
('/operator/reaver/reaver_operator_base/inspect.png', 'Operator de la collection Reaver', 159),
('/operator/reaver/reaver_operator_black/inspect.png', 'Operator de la collection Reaver', 160),
('/operator/reaver/reaver_operator_red/inspect.png', 'Operator de la collection Reaver', 161),
('/operator/reaver/reaver_operator_white/inspect.png', 'Operator de la collection Reaver', 162),
('/operator/ruination/ruination_operator_base/inspect.png', 'Operator de la collection Ruination', 163),
('/operator/ruination/ruination_operator_black/inspect.png', 'Operator de la collection Ruination', 164),
('/operator/ruination/ruination_operator_purple/inspect.png', 'Operator de la collection Ruination', 165),
('/operator/ruination/ruination_operator_white/inspect.png', 'Operator de la collection Ruination', 166),
('/operator/spectrum/spectrum_operator_base/inspect.png', 'Operator de la collection Spectrum', 167),
('/operator/spectrum/spectrum_operator_black/inspect.png', 'Operator de la collection Spectrum', 168),
('/operator/spectrum/spectrum_operator_purple/inspect.png', 'Operator de la collection Spectrum', 169),
('/operator/spectrum/spectrum_operator_red/inspect.png', 'Operator de la collection Spectrum', 170),
('/operator/lycan/lycan_operator_base/inspect.png', 'Operator de la collection Lycan s Bane', 171),
('/operator/lycan/lycan_operator_red/inspect.png', 'Operator de la collection Lycan s Bane', 172),
('/operator/lycan/lycan_operator_green/inspect.png', 'Operator de la collection Lycan s Bane', 173),
('/operator/lycan/lycan_operator_purple/inspect.png', 'Operator de la collection Lycan s Bane', 174),


('/knife/kuronami/kuronami_knife_base/icone.png', 'couteau de la collection Kuronami - base', 1),
('/knife/kuronami/kuronami_knife_black/icone.png', 'couteau de la collection Kuronami - black', 2),
('/knife/kuronami/kuronami_knife_purple/icone.png', 'couteau de la collection Kuronami - purple', 3),
('/knife/kuronami/kuronami_knife_white/icone.png', 'couteau de la collection Kuronami - white', 4),
('/knife/ion/ion_knife_base/icone.png', 'Gantelet de la collection Ion - base', 5),
('/knife/ion/ion_knife_blue/icone.png', 'Gantelet de la collection Ion - blue', 6),
('/knife/ion/ion_knife_green/icone.png', 'Gantelet de la collection Ion - green', 7),
('/knife/ion/ion_knife_orange/icone.png', 'Gantelet de la collection Ion - orange', 8),
('/knife/oni/oni_knife_base/icone.png', 'Katana de la collection Oni - base', 9),
('/knife/oni/oni_knife_black/icone.png', 'Katana de la collection Oni - black', 10),
('/knife/oni/oni_knife_green/icone.png', 'Katana de la collection Oni - green', 11),
('/knife/oni/oni_knife_white/icone.png', 'Katana de la collection Oni - white', 12),
('/classic/glitchpop/glitchpop_classic_base/icone.png', 'Classic de la collection Glitchpop - base', 13),
('/classic/glitchpop/glitchpop_classic_blue/icone.png', 'Classic de la collection Glitchpop - blue', 14),
('/classic/glitchpop/glitchpop_classic_gold/icone.png', 'Classic de la collection Glitchpop - gold', 15),
('/classic/glitchpop/glitchpop_classic_red/icone.png', 'Classic de la collection Glitchpop - red', 16),
('/classic/prime/prime_classic_base/icone.png', 'Classic de la collection Prime - base', 17),
('/classic/prime/prime_classic_blue/icone.png', 'Classic de la collection Prime - blue', 18),
('/classic/prime/prime_classic_gold/icone.png', 'Classic de la collection Prime - gold', 19),
('/classic/prime/prime_classic_red/icone.png', 'Classic de la collection Prime - red', 20),
('/classic/spectrum/spectrum_classic_base/icone.png', 'Classic de la collection Spectrum - base', 21),
('/classic/spectrum/spectrum_classic_black/icone.png', 'Classic de la collection Spectrum - black', 22),
('/classic/spectrum/spectrum_classic_purple/icone.png', 'Classic de la collection Spectrum - purple', 23),
('/classic/spectrum/spectrum_classic_red/icone.png', 'Classic de la collection Spectrum - red', 24),
('/shorty/oni/oni_shorty_base/icone.png', 'Shorty de la collection Oni - base', 25),
('/shorty/oni/oni_shorty_black/icone.png', 'Shorty de la collection Oni - black', 26),
('/shorty/oni/oni_shorty_green/icone.png', 'Shorty de la collection Oni - green', 27),
('/shorty/oni/oni_shorty_white/icone.png', 'Shorty de la collection Oni - white', 28),
('/shorty/sotl/sotl_shorty_base/icone.png', 'Shorty de la collection Sentinels of the light - base', 29),
('/shorty/sotl/sotl_shorty_purple/icone.png', 'Shorty de la collection Sentinels of the light - purple', 30),
('/shorty/sotl/sotl_shorty_pink/icone.png', 'Shorty de la collection Sentinels of the light - pink', 31),
('/shorty/sotl/sotl_shorty_green/icone.png', 'Shorty de la collection Sentinels of the light - green', 32),
('/shorty/ptc/ptc_shorty_base/icone.png', 'Shorty de la collection Prelude to Chaos - base', 33),
('/shorty/ptc/ptc_shorty_blue/icone.png', 'Shorty de la collection Prelude to Chaos - blue', 34),
('/shorty/ptc/ptc_shorty_green/icone.png', 'Shorty de la collection Prelude to Chaos - green', 35),
('/shorty/ptc/ptc_shorty_white/icone.png', 'Shorty de la collection Prelude to Chaos - white', 36),
('/frenzy/prime/prime_frenzy_base/icone.png', 'Frenzy de la collection Prime//2.0 - base', 37),
('/frenzy/prime/prime_frenzy_blue/icone.png', 'Frenzy de la collection Prime//2.0 - blue', 38),
('/frenzy/prime/prime_frenzy_gold/icone.png', 'Frenzy de la collection Prime//2.0 - gold', 39),
('/frenzy/prime/prime_frenzy_red/icone.png', 'Frenzy de la collection Prime//2.0 - red', 40),
('/frenzy/glitchpop/glitchpop_frenzy_base/icone.png', 'Frenzy de la collection Glitchpop - base', 41),
('/frenzy/glitchpop/glitchpop_frenzy_blue/icone.png', 'Frenzy de la collection Glitchpop - blue', 42),
('/frenzy/glitchpop/glitchpop_frenzy_gold/icone.png', 'Frenzy de la collection Glitchpop - gold', 43),
('/frenzy/glitchpop/glitchpop_frenzy_red/icone.png', 'Frenzy de la collection Glitchpop - red', 44),
('/frenzy/ion/ion_frenzy_base/icone.png', 'Frenzy de la collection Ion - base', 45),
('/frenzy/ion/ion_frenzy_blue/icone.png', 'Frenzy de la collection Ion - blue', 46),
('/frenzy/ion/ion_frenzy_green/icone.png', 'Frenzy de la collection Ion - green', 47),
('/frenzy/ion/ion_frenzy_orange/icone.png', 'Frenzy de la collection Ion - orange', 48),
('/ghost/gaia/gaia_ghost_base/icone.png', 'Ghost de la collection Gaia s vengeance - base', 49),
('/ghost/gaia/gaia_ghost_blue/icone.png', 'Ghost de la collection Gaia s vengeance - blue', 50),
('/ghost/gaia/gaia_ghost_green/icone.png', 'Ghost de la collection Gaia s vengeance - green', 51),
('/ghost/gaia/gaia_ghost_red/icone.png', 'Ghost de la collection Gaia s vengeance - red', 52),
('/ghost/reaver/reaver_ghost_base/icone.png', 'Ghost de la collection Reaver - base', 53),
('/ghost/reaver/reaver_ghost_black/icone.png', 'Ghost de la collection Reaver - black', 54),
('/ghost/reaver/reaver_ghost_red/icone.png', 'Ghost de la collection Reaver - red', 55),
('/ghost/reaver/reaver_ghost_white/icone.png', 'Ghost de la collection Reaver - white', 56),
('/ghost/res/res_ghost_base/icone.png', 'Ghost de la collection Radiant Entertainment System', 57),
('/ghost/res/res_ghost_purple/icone.png', 'Ghost de la collection Radiant Entertainment System', 58),
('/ghost/res/res_ghost_red/icone.png', 'Ghost de la collection Radiant Entertainment System', 59),
('/sheriff/arcane/arcane_sheriff_base/icone.png', 'Sheriff de l edition limitee Arcane', 60),
('/sheriff/reaver/reaver_sheriff_base/icone.png', 'Sheriff de la collection Reaver', 61),
('/sheriff/reaver/reaver_sheriff_black/icone.png', 'Sheriff de la collection Reaver', 62),
('/sheriff/reaver/reaver_sheriff_red/icone.png', 'Sheriff de la collection Reaver', 63),
('/sheriff/reaver/reaver_sheriff_white/icone.png', 'Sheriff de la collection Reaver', 64),
('/sheriff/sotl/sotl_sheriff_base/icone.png', 'Sheriff de la collection Sentinel of the Light', 65),
('/sheriff/sotl/sotl_sheriff_green/icone.png', 'Sheriff de la collection Sentinel of the Light', 66),
('/sheriff/sotl/sotl_sheriff_pink/icone.png', 'Sheriff de la collection Sentinel of the Light', 67),
('/sheriff/sotl/sotl_sheriff_purple/icone.png', 'Sheriff de la collection Sentinel of the Light', 68),
('/stinger/ptc/ptc_stinger_base/icone.png', 'Stinger de la collection Prelude to Chaos', 69),
('/stinger/ptc/ptc_stinger_blue/icone.png', 'Stinger de la collection Prelude to Chaos', 70),
('/stinger/ptc/ptc_stinger_green/icone.png', 'Stinger de la collection Prelude to Chaos', 71),
('/stinger/ptc/ptc_stinger_white/icone.png', 'Stinger de la collection Prelude to Chaos', 72),
('/stinger/rgx/rgx_stinger_base/icone.png', 'Stinger de la collection RGX11Z', 73),
('/stinger/rgx/rgx_stinger_blue/icone.png', 'Stinger de la collection RGX11Z', 74),
('/stinger/rgx/rgx_stinger_red/icone.png', 'Stinger de la collection RGX11Z', 75),
('/stinger/rgx/rgx_stinger_yellow/icone.png', 'Stinger de la collection RGX11Z', 76),
('/stinger/regen/regen_stinger_base/icone.png', 'Stinger de la collection Reaver', 77),
('/stinger/regen/regen_stinger_black/icone.png', 'Stinger de la collection Reaver', 78),
('/stinger/regen/regen_stinger_red/icone.png', 'Stinger de la collection Reaver', 79),
('/stinger/regen/regen_stinger_white/icone.png', 'Stinger de la collection Reaver', 80),
('/stinger/spectrum/spectrum_stinger_base/icone.png', 'Stinger de la collection Spectrum', 81),
('/stinger/spectrum/spectrum_stinger_black/icone.png', 'Stinger de la collection Spectrum', 82),
('/stinger/spectrum/spectrum_stinger_purple/icone.png', 'Stinger de la collection Spectrum', 83),
('/stinger/spectrum/spectrum_stinger_red/icone.png', 'Stinger de la collection Spectrum', 84),
('/bulldog/glitchpop/glitchpop_bulldog_base/icone.png', 'Bulldog de la collection Glitchpop', 85),
('/bulldog/glitchpop/glitchpop_bulldog_blue/icone.png', 'Bulldog de la collection Glitchpop', 86),
('/bulldog/glitchpop/glitchpop_bulldog_gold/icone.png', 'Bulldog de la collection Glitchpop', 87),
('/bulldog/glitchpop/glitchpop_bulldog_red/icone.png', 'Bulldog de la collection Glitchpop', 88),
('/bulldog/magepunk/magepunk_bulldog_base/icone.png', 'Bulldog de la collection Magepunk', 89),
('/bulldog/magepunk/magepunk_bulldog_green/icone.png', 'Bulldog de la collection Magepunk', 90),
('/bulldog/magepunk/magepunk_bulldog_orange/icone.png', 'Bulldog de la collection Magepunk', 91),
('/bulldog/magepunk/magepunk_bulldog_purple/icone.png', 'Bulldog de la collection Magepunk', 92),
('/guardian/gaia/gaia_guardian_base/icone.png', 'Guardian de la collection Gaia s vengeance', 93),
('/guardian/gaia/gaia_guardian_blue/icone.png', 'Guardian de la collection Gaia s vengeance', 94),
('/guardian/gaia/gaia_guardian_green/icone.png', 'Guardian de la collection Gaia s vengeance', 95),
('/guardian/gaia/gaia_guardian_red/icone.png', 'Guardian de la collection Gaia s vengeance', 96),
('/guardian/protocol/protocol_guardian_base/icone.png', 'Guardian de la collection Protocol', 97),
('/guardian/protocol/protocol_guardian_blue/icone.png', 'Guardian de la collection Protocol', 98),
('/guardian/protocol/protocol_guardian_orange/icone.png', 'Guardian de la collection Protocol', 99),
('/guardian/protocol/protocol_guardian_red/icone.png', 'Guardian de la collection Protocol', 100),
('/vandal/chronovoid/chronovoid_vandal_base/icone.png', 'Vandal de la collection Chronovoid', 101),
('/vandal/chronovoid/chronovoid_vandal_black/icone.png', 'Vandal de la collection Chronovoid', 102),
('/vandal/chronovoid/chronovoid_vandal_purple/icone.png', 'Vandal de la collection Chronovoid', 103),
('/vandal/chronovoid/chronovoid_vandal_red/icone.png', 'Vandal de la collection Chronovoid', 104),
('/vandal/glitchpop/glitchpop_vandal_base/icone.png', 'Vandal de la collection Glitchpop', 105),
('/vandal/glitchpop/glitchpop_vandal_blue/icone.png', 'Vandal de la collection Glitchpop', 106),
('/vandal/glitchpop/glitchpop_vandal_gold/icone.png', 'Vandal de la collection Glitchpop', 107),
('/vandal/glitchpop/glitchpop_vandal_red/icone.png', 'Vandal de la collection Glitchpop', 108),
('/vandal/prime/prime_vandal_base/icone.png', 'Vandal de la collection Prime', 109),
('/vandal/prime/prime_vandal_blue/icone.png', 'Vandal de la collection Prime', 110),
('/vandal/prime/prime_vandal_gold/icone.png', 'Vandal de la collection Prime', 111),
('/vandal/prime/prime_vandal_red/icone.png', 'Vandal de la collection Prime', 112),
('/vandal/rgx/rgx_vandal_base/icone.png', 'Vandal de la collection RGX11Z', 113),
('/vandal/rgx/rgx_vandal_blue/icone.png', 'Vandal de la collection RGX11Z', 114),
('/vandal/rgx/rgx_vandal_red/icone.png', 'Vandal de la collection RGX11Z', 115),
('/vandal/rgx/rgx_vandal_yellow/icone.png', 'Vandal de la collection RGX11Z', 116),
('/vandal/reaver/reaver_vandal_base/icone.png', 'Vandal de la collection Reaver', 117),
('/vandal/reaver/reaver_vandal_black/icone.png', 'Vandal de la collection Reaver', 118),
('/vandal/reaver/reaver_vandal_red/icone.png', 'Vandal de la collection Reaver', 119),
('/vandal/reaver/reaver_vandal_white/icone.png', 'Vandal de la collection Reaver', 120),
('/phantom/champions/champions_phantom_base/icone.png', 'Phantom de la collection Champions', 121),
('/phantom/glitchpop/glitchpop_phantom_base/icone.png', 'Phantom de la collection Glitchpop', 122),
('/phantom/glitchpop/glitchpop_phantom_blue/icone.png', 'Phantom de la collection Glitchpop', 123),
('/phantom/glitchpop/glitchpop_phantom_gold/icone.png', 'Phantom de la collection Glitchpop', 124),
('/phantom/glitchpop/glitchpop_phantom_red/icone.png', 'Phantom de la collection Glitchpop', 125),
('/phantom/oni/oni_phantom_base/icone.png', 'Phantom de la collection Oni', 126),
('/phantom/oni/oni_phantom_black/icone.png', 'Phantom de la collection Oni', 127),
('/phantom/oni/oni_phantom_green/icone.png', 'Phantom de la collection Oni', 128),
('/phantom/oni/oni_phantom_white/icone.png', 'Phantom de la collection Oni', 129),
('/phantom/ruination/ruination_phantom_base/icone.png', 'Phantom de la collection Ruination', 130),
('/phantom/ruination/ruination_phantom_blue/icone.png', 'Phantom de la collection Ruination', 131),
('/phantom/ruination/ruination_phantom_red/icone.png', 'Phantom de la collection Ruination', 132),
('/phantom/ruination/ruination_phantom_yellow/icone.png', 'Phantom de la collection Ruination', 133),
('/phantom/spectrum/spectrum_phantom_base/icone.png', 'Phantom de la collection Spectrum', 134),
('/phantom/spectrum/spectrum_phantom_black/icone.png', 'Phantom de la collection Spectrum', 135),
('/phantom/spectrum/spectrum_phantom_purple/icone.png', 'Phantom de la collection Spectrum', 136),
('/phantom/spectrum/spectrum_phantom_red/icone.png', 'Phantom de la collection Spectrum', 137),
('/phantom/valorantgov/valorantgov_phantom_base/icone.png', 'Phantom de la collection Valorant Go', 138),
('/phantom/valorantgov/valorantgov_phantom_black/icone.png', 'Phantom de la collection Valorant Go', 139),
('/phantom/valorantgov/valorantgov_phantom_purple/icone.png', 'Phantom de la collection Valorant Go', 140),
('/phantom/valorantgov/valorantgov_phantom_red/icone.png', 'Phantom de la collection Valorant Go', 141),
('/phantom/smorgasbord/smorgasbord_phantom_base/icone.png', 'Phantom de la collection Smorgasbord', 142),
('/phantom/smorgasbord/smorgasbord_phantom_green/icone.png', 'Phantom de la collection Smorgasbord', 143),
('/phantom/smorgasbord/smorgasbord_phantom_purple/icone.png', 'Phantom de la collection Smorgasbord', 144),
('/phantom/smorgasbord/smorgasbord_phantom_red/icone.png', 'Phantom de la collection Smorgasbord', 145),
('/phantom/smorgasbord/smorgasbord_phantom_yellow/icone.png', 'Phantom de la collection Smorgasbord', 146),
('/operator/ion/ion_operator_base/icone.png', 'Operator de la collection Ion', 147),
('/operator/ion/ion_operator_blue/icone.png', 'Operator de la collection Ion', 148),
('/operator/ion/ion_operator_green/icone.png', 'Operator de la collection Ion', 149),
('/operator/ion/ion_operator_yellow/icone.png', 'Operator de la collection Ion', 150),
('/operator/rgx/rgx_operator_base/icone.png', 'Operator de la collection RGX11Z', 151),
('/operator/rgx/rgx_operator_blue/icone.png', 'Operator de la collection RGX11Z', 152),
('/operator/rgx/rgx_operator_red/icone.png', 'Operator de la collection RGX11Z', 153),
('/operator/rgx/rgx_operator_yellow/icone.png', 'Operator de la collection RGX11Z', 154),
('/operator/elderflame/elderflame_operator_base/icone.png', 'Operator de la collection Elderflame', 155),
('/operator/elderflame/elderflame_operator_blue/icone.png', 'Operator de la collection Elderflame', 156),
('/operator/elderflame/elderflame_operator_purple/icone.png', 'Operator de la collection Elderflame', 157),
('/operator/elderflame/elderflame_operator_red/icone.png', 'Operator de la collection Elderflame', 158),
('/operator/reaver/reaver_operator_base/icone.png', 'Operator de la collection Reaver', 159),
('/operator/reaver/reaver_operator_black/icone.png', 'Operator de la collection Reaver', 160),
('/operator/reaver/reaver_operator_red/icone.png', 'Operator de la collection Reaver', 161),
('/operator/reaver/reaver_operator_white/icone.png', 'Operator de la collection Reaver', 162),
('/operator/ruination/ruination_operator_base/icone.png', 'Operator de la collection Ruination', 163),
('/operator/ruination/ruination_operator_black/icone.png', 'Operator de la collection Ruination', 164),
('/operator/ruination/ruination_operator_purple/icone.png', 'Operator de la collection Ruination', 165),
('/operator/ruination/ruination_operator_white/icone.png', 'Operator de la collection Ruination', 166),
('/operator/spectrum/spectrum_operator_base/icone.png', 'Operator de la collection Spectrum', 167),
('/operator/spectrum/spectrum_operator_black/icone.png', 'Operator de la collection Spectrum', 168),
('/operator/spectrum/spectrum_operator_purple/icone.png', 'Operator de la collection Spectrum', 169),
('/operator/spectrum/spectrum_operator_red/icone.png', 'Operator de la collection Spectrum', 170),
('/operator/lycan/lycan_operator_base/icone.png', 'Operator de la collection Lycan s Bane', 171),
('/operator/lycan/lycan_operator_red/icone.png', 'Operator de la collection Lycan s Bane', 172),
('/operator/lycan/lycan_operator_green/icone.png', 'Operator de la collection Lycan s Bane', 173),
('/operator/lycan/lycan_operator_purple/icone.png', 'Operator de la collection Lycan s Bane', 174);

