-- insertion des différentes collection de la table collection
INSERT INTO collections (collection_name) VALUES
    ('Kuronami'),
    ('Ion'),
    ('Oni'),
    ('Glitchpop'),
    ('Prime'),
    ('Prime//2.0'),
    ('Spectrum'),
    ('Sentinel of the light'),
    ('Prelude to Chaos'),
    ("Gaia's vengance"),
    ('Reaver'),
    ('Radiant Entertainment System'),
    ('Arcane'),
    ('RGX'),
    ('Magepunk'),
    ('Elderflame'),
    ('Convex'),
    ('Champion 2021'),
    ('Champion 2022'),
    ('Champion 2023');

--insertion des nom d'armes
INSERT INTO weapons (weapon_name) VALUES
    ('Knife'),
    ('Classic'),
    ('Shorty'),
    ('Frenzy'),
    ('Ghost'),
    ('Sheriff'),
    ('Stinger'),
    ('Spectre'),
    ('Bucky'),
    ('Judge'),
    ('Bulldog'),
    ('Guardian'),
    ('Phantom'),
    ('Vandal'),
    ('Marshall'),
    ('Operator'),
    ('Ares'),
    ('Odin');

--insertion des variantes
INSERT INTO variantes (variante_name) VALUES
    ('kuronami_base'),
    ('kuronami_black'),
    ('kuronami_purple'),
    ('kuronami_white'),
    ('ion_base'),
    ('ion_blue'),
    ('ion_green'),
    ('ion_orange'),
    ('oni_base'),
    ('oni_black'),
    ('oni_green'),
    ('oni_white'),
    ('glitchpop_base'),
    ('glitchpop_blue'),
    ('glitchpop_gold'),
    ('glitchpop_red'),
    ('prime_base'),
    ('prime_blue'),
    ('prime_orange'),
    ('prime_yellow'),
    ('prime2_base'),
    ('prime2_blue'),
    ('prime2_gold'),
    ('prime2_red'),
    ('spectrum_base'),
    ('spectrum_black'),
    ('spectrum_purple'),
    ('spectrum_red'),
    ('sotl_base'),
    ('sotl_purple'),
    ('sotl_pink'),
    ('sotl_green'),
    ('ptc_base'),
    ('ptc_blue'),
    ('ptc_green'),
    ('ptc_white'),
    ('gaia_base'),
    ('gaia_blue'),
    ('gaia_green'),
    ('gaia_red'),
    ('reaver_base'),
    ('reaver_black'),
    ('reaver_red'),
    ('reaver_white'),
    ('res_base'),
    ('res_red'),
    ('res_purple'),
    ('arcane_base'),
    ('rgx_base'),
    ('rgx_blue'),
    ('rgx_red'),
    ('rgx_yellow'),
    ('magepunk_base'),
    ('magepunk_green'),
    ('magepunk_purple'),
    ('magepunk_yellow'),
    ('elderflame_base'),
    ('elderflame_black'),
    ('elderflame_blue'),
    ('elderflame_red'),
    ('convex_base'),
    ('champion21_base'),
    ('champion22_base'),
    ('champion23_base');    

-- insertion des différents skins
INSERT INTO products (product_name, price, reduction, description, weapon_id, collection_id, variante_id) VALUES
    ('Kuronami Knife', 2000, NULL, 'couteau de la collection Kuronami - base', 1, 1, 1),
    ('Kuronami Knife', 2000, NULL, 'couteau de la collection Kuronami - black', 1, 1, 2),
    ('Kuronami Knife', 2000, NULL, 'couteau de la collection Kuronami - purple', 1, 1, 3),
    ('Kuronami Knife', 2000, NULL, 'couteau de la collection Kuronami - white', 1, 1, 4),
    ('Ion Knife', 2000, NULL, 'Gantelet de la collection Ion - base', 1, 2, 5),
    ('Ion Knife', 2000, NULL, 'Gantelet de la collection Ion - blue', 1, 2, 6),
    ('Ion Knife', 2000, NULL, 'Gantelet de la collection Ion - green', 1, 2, 7),
    ('Ion Knife', 2000, NULL, 'Gantelet de la collection Ion - orange', 1, 2, 8),
    ('Oni Knife', 2000, NULL, 'Katana de la collection Oni - base', 1, 3, 9),
    ('Oni Knife', 2000, NULL, 'Katana de la collection Oni - black', 1, 3, 10),
    ('Oni Knife', 2000, NULL, 'Katana de la collection Oni - green', 1, 3, 11),
    ('Oni Knife', 2000, NULL, 'Katana de la collection Oni - white', 1, 3, 12),
    ('Glitchpop Classic', 2000, NULL, 'Classic de la collection Glitchpop - base', 2, 4, 13),
    ('Glitchpop Classic', 2000, NULL, 'Classic de la collection Glitchpop - blue', 2, 4, 14),
    ('Glitchpop Classic', 2000, NULL, 'Classic de la collection Glitchpop - gold', 2, 4, 15),
    ('Glitchpop Classic', 2000, NULL, 'Classic de la collection Glitchpop - red', 2, 4, 16),
    ('Prime Classic', 2000, NULL, 'Classic de la collection Prime - base', 2, 5, 17),
    ('Prime Classic', 2000, NULL, 'Classic de la collection Prime - blue', 2, 5, 18),
    ('Prime Classic', 2000, NULL, 'Classic de la collection Prime - gold', 2, 5, 19),
    ('Prime Classic', 2000, NULL, 'Classic de la collection Prime - red', 2, 5, 20),
    ('Spectrum Classis', 2000, NULL, 'Classic de la collection Spectrum - base', 2, 6, 25),
    ('Spectrum Classis', 2000, NULL, 'Classic de la collection Spectrum - black', 2, 6, 26),
    ('Spectrum Classis', 2000, NULL, 'Classic de la collection Spectrum - purple', 2, 6, 27),
    ('Spectrum Classis', 2000, NULL, 'Classic de la collection Spectrum - red', 2, 6, 28),
    ('Oni Shorty', 2000, NULL, 'Shorty de la collection Oni - base', 3, 3, 9),
    ('Oni Shorty', 2000, NULL, 'Shorty de la collection Oni - black', 3, 3, 10),
    ('Oni Shorty', 2000, NULL, 'Shorty de la collection Oni - green', 3, 3, 11),
    ('Oni Shorty', 2000, NULL, 'Shorty de la collection Oni - white', 3, 3, 12),
    ('SOTL Shorty', 2000, NULL, 'Shorty de la collection Sentinels of the light - base', 3, 7, 29),
    ('SOTL Shorty', 2000, NULL, 'Shorty de la collection Sentinels of the light - purple', 3, 7, 30),
    ('SOTL Shorty', 2000, NULL, 'Shorty de la collection Sentinels of the light - pink', 3, 7, 31),
    ('SOTL Shorty', 2000, NULL, 'Shorty de la collection Sentinels of the light - green', 3, 7, 32),
    ('PTC Shorty', 2000, NULL, 'Shorty de la collection Prelude to Chaos - base', 3, 8, 33),
    ('PTC Shorty', 2000, NULL, 'Shorty de la collection Prelude to Chaos - blue', 3, 8, 34),
    ('PTC Shorty', 2000, NULL, 'Shorty de la collection Prelude to Chaos - green', 3, 8, 35),
    ('PTC Shorty', 2000, NULL, 'Shorty de la collection Prelude to Chaos - white', 3, 8, 36),
    ('Prime Frenzy', 2000, NULL, 'Frenzy de la collection Prime//2.0 - base', 4, 5, 21),
    ('Prime Frenzy', 2000, NULL, 'Frenzy de la collection Prime//2.0 - blue', 4, 5, 22),
    ('Prime Frenzy', 2000, NULL, 'Frenzy de la collection Prime//2.0 - gold', 4, 5, 23),
    ('Prime Frenzy', 2000, NULL, 'Frenzy de la collection Prime//2.0 - red', 4, 5, 24),
    ('Glitchpop Frenzy', 2000, NULL, 'Frenzy de la collection Glitchpop - base', 4, 4, 13),
    ('Glitchpop Frenzy', 2000, NULL, 'Frenzy de la collection Glitchpop - blue', 4, 4, 14),
    ('Glitchpop Frenzy', 2000, NULL, 'Frenzy de la collection Glitchpop - gold', 4, 4, 15),
    ('Glitchpop Frenzy', 2000, NULL, 'Frenzy de la collection Glitchpop - red', 4, 4, 16),
    ('Ion Frenzy', 2000, NULL, 'Frenzy de la collection Ion - base', 4, 2, 5),
    ('Ion Frenzy', 2000, NULL, 'Frenzy de la collection Ion - blue', 4, 2, 6),
    ('Ion Frenzy', 2000, NULL, 'Frenzy de la collection Ion - green', 4, 2, 7),
    ('Ion Frenzy', 2000, NULL, 'Frenzy de la collection Ion - orange', 4, 2, 8),
    ('Gaia Ghost', 2000, NULL, 'Ghost de la collection Gaia s vengeance - base', 5, 9, 37),
    ('Gaia Ghost', 2000, NULL, 'Ghost de la collection Gaia s vengeance - blue', 5, 9, 38),
    ('Gaia Ghost', 2000, NULL, 'Ghost de la collection Gaia s vengeance - green', 5, 9, 39),
    ('Gaia Ghost', 2000, NULL, 'Ghost de la collection Gaia s vengeance - red', 5, 9, 40),
    ('Reaver Ghost', 2000, NULL, 'Ghost de la collection Reaver - base', 5, 10, 41),
    ('Reaver Ghost', 2000, NULL, 'Ghost de la collection Reaver - black', 5, 10, 42),
    ('Reaver Ghost', 2000, NULL, 'Ghost de la collection Reaver - red', 5, 10, 43),
    ('Reaver Ghost', 2000, NULL, 'Ghost de la collection Reaver - white', 5, 10, 44),




    --!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!j'en suis là !!!!!!!!!!!!!!!!!!!!!!!!!!!!!





    ('RES Ghost', 2000, NULL, 'Ghost de la collection Radiant Entertainment System', 5, 11),
    ('Arcane Sheriff', 2000, NULL, 'Sheriff de l edition limitée Arcane', 6, 12), 
    ('Ion Sheriff', 2000, NULL, 'Sheriff de la collection Ion', 6, 2),
    ('Reaver Sheriff', 2000, NULL, 'Sheriff de la collection Reaver', 6, 10), 
    ('SOTL Sherill', 2000, NULL, 'Sheriff de la collection Sentinel of the Light', 6, 7),
    ('PTC Stinger', 2000, NULL, 'Stinger de la collection Prelude to Chaos', 7, 8),
    ('RGX Stinger', 2000, NULL, 'Stinger de la collection RGX', 7, 13),
    ('Reaver Spectre', 2000, NULL, 'Spectre de la collection Reaver', 8, 10),
    ('Magepunk Spectre', 2000, NULL, 'Spectre de la collection MagePunk', 8, 14),
    ('Kuronami Spectre', 2000, NULL, 'Spectre de la collection Kuronami', 8, 1), 
    ('Prime Spectre', 2000, NULL, 'Spectre de la collection Prime', 8, 5),
    ('Oni Bucky', 2000, NULL, 'Bucky de la collection Oni', 9, 3), 
    ('Gaia Bucky', 2000, NULL, 'Bucky de la collection Gaia s vengeance', 9, 9),
    ('Prime Bucky', 2000, NULL, 'Bucky de la collection Prime', 9, 5),
    ('Glitchpop Judge', 2000, NULL, 'Judge de la collection Glitchpop', 10, 4), 
    ('Elderflame Judge', 2000, NULL, 'Judge de la collection Elderflame', 10, 15), 
    ('Convex Judge', 2000, NULL, 'Judge de la collection Convex', 10, 16),
    ('RES Bulldog', 2000, NULL, 'Bulldog de la collection Radiant Entertainment System', 11, 11),
    ('Oni Bulldog', 2000, NULL, 'Bulldog de la collection Oni', 11, 3),
    ('Spectrum Bulldog', 2000, NULL, 'Bulldog de la collection Spectrum', 11, 6),
    ('Gaia Guardian', 2000, NULL, 'Guardian de la collection Gaia s vengeance', 12, 9),
    ('Prime Guardian', 2000, NULL, 'Guardian de la collection Prime', 12, 5),
    ('Reaver Guardian', 2000, NULL, 'Guardian de la collection Reaver', 12, 10),
    ('Champion22 Phantom', 2000, NULL, 'Phantom de la collection Champion 22', 13, 17),
    ('Glitchpop Phantom', 2000, NULL, 'Phantom de la collection Glitchpop', 13, 4),
    ('Prime Phantom', 2000, NULL, 'Phantom de la collection Prime', 13, 5),
    ('Oni Phantom', 2000, NULL, 'Phantom de la collection Oni', 13, 3),
    ('RES Phantom', 2000, NULL, 'Phantom de la collection Radiant Entertainment System', 13, 11),
    ('Champion21 Vandal', 2000, NULL, 'Vandal de la collection Champion 21', 13, 18),
    ('Champion23 Vandal', 2000, NULL, 'Vandal de la collection Champion 23', 13, 19),
    ('Gaia Vandal', 2000, NULL, 'Vandal de la collection Gaia s vengeance', 13, 9),
    ('Ion Vandal', 2000, NULL, 'Vandal de la collection Ion', 13, 2),
    ('Magepunk Vandal', 2000, NULL, 'Vandal de la collection Magepunk', 13, 14),
    ('PTC Vandal', 2000, NULL, 'Vandal de la collection Prelude to Chaos', 13, 8),
    ('Gaia Marshall', 2000, NULL, 'Marshall de la collection Gaia s vengeance', 14, 9),
    ('Magepunk Marshall', 2000, NULL, 'Marshall de la collection Magepunk', 14, 14),
    ('Reaver Operator', 2000, NULL, 'Operator de la collection Reaver', 15, 10),
    ('Glitchpop Operator', 2000, NULL, 'Operator de la collection Glitchpop', 15, 4),
    ('RES Operator', 2000, NULL, 'Operator de la collection Radiant Entertainment System', 15, 11),
    ('SOTL Ares', 2000, NULL, 'Ares de la collection Sentinel of the Light', 16, 7),
    ('Ion Ares', 2000, NULL, 'Ares de la collection Ion', 16, 2),
    ('Oni Ares', 2000, NULL, 'Ares de la collection Oni', 16, 3),
    ('Prime Odin', 2000, NULL, 'Odin de la collection Prime', 17, 5),
    ('Reaver Odin', 2000, NULL, 'Odin de la collection Reaver', 17, 10),
    ('Glitchpop Odin', 2000, NULL, 'Odin de la collection Glitchpop', 17, 4);
    






