INSERT INTO armes (arme_name) VALUES
    ('Knife'),
    ('Classic'),
    ('Shorty'),
    ('Frenzy'),
    ('Ghost'),
    ('Sheriff'),
    ('Stinger'),
    ('Spectre'),
    ('Bucky'),
    ('Judge'),
    ('Bulldog'),
    ('Guardian'),
    ('Phantom'),
    ('Vandal'),
    ('Marshall'),
    ('Operator'),
    ('Ares'),
    ('Odin');

INSERT INTO collections (collection_name) VALUES
    ('Kuronami'),
    ('Ion'),
    ('Oni'),
    ('Glitchpop'),
    ('Prime'),
    ('Spectrum'),
    ('Sentinel of the light'),
    ('Prelude to Chaos'),
    ("Gaia's vengance"),
    ('Reaver'),
    ('Radiant Entertainment System'),
    ('Arcane'),
    ('RGX'),
    ('Magepunk'),
    ('Elderflame'),
    ('Convex'),
    ('Champion 2021'),
    ('Champion 2022'),
    ('Champion 2023');

INSERT INTO skin (collection_id, arme_id, price, reduction, image_path, icone_path, background_path, description) VALUES
(1, 1, 20, NULL, NULL, NULL, NULL, Couteau Kuronami),
(2, 1, 20, NULL, NULL, NULL, NULL, Couteau Ion),